/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTeamsRouteImport } from './routes/_layout/teams'
import { Route as LayoutSearchRouteImport } from './routes/_layout/search'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutTeamsIndexRouteImport } from './routes/_layout/teams/index'
import { Route as LayoutSeasonsIndexRouteImport } from './routes/_layout/seasons/index'
import { Route as LayoutSearchIndexRouteImport } from './routes/_layout/search/index'
import { Route as LayoutLoginIndexRouteImport } from './routes/_layout/login/index'
import { Route as LayoutDashboardIndexRouteImport } from './routes/_layout/dashboard/index'
import { Route as LayoutAboutIndexRouteImport } from './routes/_layout/about/index'
import { Route as LayoutTeamsSelectionRouteImport } from './routes/_layout/teams/selection'
import { Route as LayoutTeamsMapRouteImport } from './routes/_layout/teams/map'
import { Route as LayoutTeamsCompareRouteImport } from './routes/_layout/teams/compare'
import { Route as LayoutTeamTeamIdRouteImport } from './routes/_layout/team/$teamId'
import { Route as LayoutSeasonYearRouteImport } from './routes/_layout/season/$year'
import { Route as LayoutMaratonTableRouteImport } from './routes/_layout/maraton/table'
import { Route as LayoutTeamTeamIdIndexRouteImport } from './routes/_layout/team/$teamId/index'
import { Route as LayoutDashboardTeamsIndexRouteImport } from './routes/_layout/dashboard/teams/index'
import { Route as LayoutDashboardSeasonsIndexRouteImport } from './routes/_layout/dashboard/seasons/index'
import { Route as LayoutTeamTeamIdSeasonsRouteImport } from './routes/_layout/team/$teamId/seasons'
import { Route as LayoutTeamTeamIdSeasonIdRouteImport } from './routes/_layout/team/$teamId/$seasonId'
import { Route as LayoutSeasonYearPlayoffRouteImport } from './routes/_layout/season/$year/playoff'
import { Route as LayoutMaratonTableMaratonTableRouteImport } from './routes/_layout/maraton/table/$maratonTable'
import { Route as LayoutMaratonRecordsStreaksRouteImport } from './routes/_layout/maraton/records/streaks'
import { Route as LayoutMaratonRecordsStatsRouteImport } from './routes/_layout/maraton/records/stats'
import { Route as LayoutMaratonRecordsScoredRouteImport } from './routes/_layout/maraton/records/scored'
import { Route as LayoutMaratonRecordsPointsRouteImport } from './routes/_layout/maraton/records/points'
import { Route as LayoutMaratonRecordsConcededRouteImport } from './routes/_layout/maraton/records/conceded'
import { Route as LayoutDashboardTeamsAddRouteImport } from './routes/_layout/dashboard/teams/add'
import { Route as LayoutDashboardTeamTeamIdRouteImport } from './routes/_layout/dashboard/team/$teamId'
import { Route as LayoutDashboardSeasonSeasonIdRouteImport } from './routes/_layout/dashboard/season/$seasonId'
import { Route as LayoutDashboardGamesTodayRouteImport } from './routes/_layout/dashboard/games/$today'
import { Route as LayoutSeasonYearGroupIndexRouteImport } from './routes/_layout/season/$year/$group/index'
import { Route as LayoutSeasonYearPlayoffTableRouteImport } from './routes/_layout/season/$year/playoff/table'
import { Route as LayoutSeasonYearPlayoffStatsRouteImport } from './routes/_layout/season/$year/playoff/stats'
import { Route as LayoutSeasonYearPlayoffMapRouteImport } from './routes/_layout/season/$year/playoff/map'
import { Route as LayoutSeasonYearPlayoffGamesRouteImport } from './routes/_layout/season/$year/playoff/games'
import { Route as LayoutSeasonYearGroupTablesRouteImport } from './routes/_layout/season/$year/$group/tables'
import { Route as LayoutSeasonYearGroupStatsRouteImport } from './routes/_layout/season/$year/$group/stats'
import { Route as LayoutSeasonYearGroupMapRouteImport } from './routes/_layout/season/$year/$group/map'
import { Route as LayoutSeasonYearGroupIntervalRouteImport } from './routes/_layout/season/$year/$group/interval'
import { Route as LayoutSeasonYearGroupGamesRouteImport } from './routes/_layout/season/$year/$group/games'
import { Route as LayoutSeasonYearGroupDevelopmentRouteImport } from './routes/_layout/season/$year/$group/development'
import { Route as LayoutDashboardGamesTodayGameIdRouteImport } from './routes/_layout/dashboard/games/$today/$gameId'
import { Route as LayoutSeasonYearGroupTablesTableRouteImport } from './routes/_layout/season/$year/$group/tables/$table'
import { Route as LayoutDashboardSeasonSeasonIdSerieIdSerieIdRouteImport } from './routes/_layout/dashboard/season/$seasonId/$serieId/$serieId'
import { Route as LayoutDashboardGamesTodayGameIdResultRouteImport } from './routes/_layout/dashboard/games/$today/$gameId/result'
import { Route as LayoutDashboardGamesTodayGameIdDateRouteImport } from './routes/_layout/dashboard/games/$today/$gameId/date'

const LayoutUnauthorizedIndexLazyRouteImport = createFileRoute(
  '/_layout/unauthorized/',
)()

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTeamsRoute = LayoutTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSearchRoute = LayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUnauthorizedIndexLazyRoute =
  LayoutUnauthorizedIndexLazyRouteImport.update({
    id: '/unauthorized/',
    path: '/unauthorized/',
    getParentRoute: () => LayoutRoute,
  } as any).lazy(() =>
    import('./routes/_layout/unauthorized/index.lazy').then((d) => d.Route),
  )
const LayoutTeamsIndexRoute = LayoutTeamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutTeamsRoute,
} as any)
const LayoutSeasonsIndexRoute = LayoutSeasonsIndexRouteImport.update({
  id: '/seasons/',
  path: '/seasons/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSearchIndexRoute = LayoutSearchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutSearchRoute,
} as any)
const LayoutLoginIndexRoute = LayoutLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardIndexRoute = LayoutDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutDashboardRoute,
} as any)
const LayoutAboutIndexRoute = LayoutAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTeamsSelectionRoute = LayoutTeamsSelectionRouteImport.update({
  id: '/selection',
  path: '/selection',
  getParentRoute: () => LayoutTeamsRoute,
} as any)
const LayoutTeamsMapRoute = LayoutTeamsMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => LayoutTeamsRoute,
} as any)
const LayoutTeamsCompareRoute = LayoutTeamsCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => LayoutTeamsRoute,
} as any)
const LayoutTeamTeamIdRoute = LayoutTeamTeamIdRouteImport.update({
  id: '/team/$teamId',
  path: '/team/$teamId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSeasonYearRoute = LayoutSeasonYearRouteImport.update({
  id: '/season/$year',
  path: '/season/$year',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMaratonTableRoute = LayoutMaratonTableRouteImport.update({
  id: '/maraton/table',
  path: '/maraton/table',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTeamTeamIdIndexRoute = LayoutTeamTeamIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutTeamTeamIdRoute,
} as any)
const LayoutDashboardTeamsIndexRoute =
  LayoutDashboardTeamsIndexRouteImport.update({
    id: '/teams/',
    path: '/teams/',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)
const LayoutDashboardSeasonsIndexRoute =
  LayoutDashboardSeasonsIndexRouteImport.update({
    id: '/seasons/',
    path: '/seasons/',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)
const LayoutTeamTeamIdSeasonsRoute = LayoutTeamTeamIdSeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => LayoutTeamTeamIdRoute,
} as any)
const LayoutTeamTeamIdSeasonIdRoute =
  LayoutTeamTeamIdSeasonIdRouteImport.update({
    id: '/$seasonId',
    path: '/$seasonId',
    getParentRoute: () => LayoutTeamTeamIdRoute,
  } as any)
const LayoutSeasonYearPlayoffRoute = LayoutSeasonYearPlayoffRouteImport.update({
  id: '/playoff',
  path: '/playoff',
  getParentRoute: () => LayoutSeasonYearRoute,
} as any)
const LayoutMaratonTableMaratonTableRoute =
  LayoutMaratonTableMaratonTableRouteImport.update({
    id: '/$maratonTable',
    path: '/$maratonTable',
    getParentRoute: () => LayoutMaratonTableRoute,
  } as any)
const LayoutMaratonRecordsStreaksRoute =
  LayoutMaratonRecordsStreaksRouteImport.update({
    id: '/maraton/records/streaks',
    path: '/maraton/records/streaks',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutMaratonRecordsStatsRoute =
  LayoutMaratonRecordsStatsRouteImport.update({
    id: '/maraton/records/stats',
    path: '/maraton/records/stats',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutMaratonRecordsScoredRoute =
  LayoutMaratonRecordsScoredRouteImport.update({
    id: '/maraton/records/scored',
    path: '/maraton/records/scored',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutMaratonRecordsPointsRoute =
  LayoutMaratonRecordsPointsRouteImport.update({
    id: '/maraton/records/points',
    path: '/maraton/records/points',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutMaratonRecordsConcededRoute =
  LayoutMaratonRecordsConcededRouteImport.update({
    id: '/maraton/records/conceded',
    path: '/maraton/records/conceded',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutDashboardTeamsAddRoute = LayoutDashboardTeamsAddRouteImport.update({
  id: '/teams/add',
  path: '/teams/add',
  getParentRoute: () => LayoutDashboardRoute,
} as any)
const LayoutDashboardTeamTeamIdRoute =
  LayoutDashboardTeamTeamIdRouteImport.update({
    id: '/team/$teamId',
    path: '/team/$teamId',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)
const LayoutDashboardSeasonSeasonIdRoute =
  LayoutDashboardSeasonSeasonIdRouteImport.update({
    id: '/season/$seasonId',
    path: '/season/$seasonId',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)
const LayoutDashboardGamesTodayRoute =
  LayoutDashboardGamesTodayRouteImport.update({
    id: '/games/$today',
    path: '/games/$today',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)
const LayoutSeasonYearGroupIndexRoute =
  LayoutSeasonYearGroupIndexRouteImport.update({
    id: '/$group/',
    path: '/$group/',
    getParentRoute: () => LayoutSeasonYearRoute,
  } as any)
const LayoutSeasonYearPlayoffTableRoute =
  LayoutSeasonYearPlayoffTableRouteImport.update({
    id: '/table',
    path: '/table',
    getParentRoute: () => LayoutSeasonYearPlayoffRoute,
  } as any)
const LayoutSeasonYearPlayoffStatsRoute =
  LayoutSeasonYearPlayoffStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => LayoutSeasonYearPlayoffRoute,
  } as any)
const LayoutSeasonYearPlayoffMapRoute =
  LayoutSeasonYearPlayoffMapRouteImport.update({
    id: '/map',
    path: '/map',
    getParentRoute: () => LayoutSeasonYearPlayoffRoute,
  } as any)
const LayoutSeasonYearPlayoffGamesRoute =
  LayoutSeasonYearPlayoffGamesRouteImport.update({
    id: '/games',
    path: '/games',
    getParentRoute: () => LayoutSeasonYearPlayoffRoute,
  } as any)
const LayoutSeasonYearGroupTablesRoute =
  LayoutSeasonYearGroupTablesRouteImport.update({
    id: '/$group/tables',
    path: '/$group/tables',
    getParentRoute: () => LayoutSeasonYearRoute,
  } as any)
const LayoutSeasonYearGroupStatsRoute =
  LayoutSeasonYearGroupStatsRouteImport.update({
    id: '/$group/stats',
    path: '/$group/stats',
    getParentRoute: () => LayoutSeasonYearRoute,
  } as any)
const LayoutSeasonYearGroupMapRoute =
  LayoutSeasonYearGroupMapRouteImport.update({
    id: '/$group/map',
    path: '/$group/map',
    getParentRoute: () => LayoutSeasonYearRoute,
  } as any)
const LayoutSeasonYearGroupIntervalRoute =
  LayoutSeasonYearGroupIntervalRouteImport.update({
    id: '/$group/interval',
    path: '/$group/interval',
    getParentRoute: () => LayoutSeasonYearRoute,
  } as any)
const LayoutSeasonYearGroupGamesRoute =
  LayoutSeasonYearGroupGamesRouteImport.update({
    id: '/$group/games',
    path: '/$group/games',
    getParentRoute: () => LayoutSeasonYearRoute,
  } as any)
const LayoutSeasonYearGroupDevelopmentRoute =
  LayoutSeasonYearGroupDevelopmentRouteImport.update({
    id: '/$group/development',
    path: '/$group/development',
    getParentRoute: () => LayoutSeasonYearRoute,
  } as any)
const LayoutDashboardGamesTodayGameIdRoute =
  LayoutDashboardGamesTodayGameIdRouteImport.update({
    id: '/$gameId',
    path: '/$gameId',
    getParentRoute: () => LayoutDashboardGamesTodayRoute,
  } as any)
const LayoutSeasonYearGroupTablesTableRoute =
  LayoutSeasonYearGroupTablesTableRouteImport.update({
    id: '/$table',
    path: '/$table',
    getParentRoute: () => LayoutSeasonYearGroupTablesRoute,
  } as any)
const LayoutDashboardSeasonSeasonIdSerieIdSerieIdRoute =
  LayoutDashboardSeasonSeasonIdSerieIdSerieIdRouteImport.update({
    id: '/$serieId/$serieId',
    path: '/$serieId/$serieId',
    getParentRoute: () => LayoutDashboardSeasonSeasonIdRoute,
  } as any)
const LayoutDashboardGamesTodayGameIdResultRoute =
  LayoutDashboardGamesTodayGameIdResultRouteImport.update({
    id: '/result',
    path: '/result',
    getParentRoute: () => LayoutDashboardGamesTodayGameIdRoute,
  } as any)
const LayoutDashboardGamesTodayGameIdDateRoute =
  LayoutDashboardGamesTodayGameIdDateRouteImport.update({
    id: '/date',
    path: '/date',
    getParentRoute: () => LayoutDashboardGamesTodayGameIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof LayoutDashboardRouteWithChildren
  '/search': typeof LayoutSearchRouteWithChildren
  '/teams': typeof LayoutTeamsRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/maraton/table': typeof LayoutMaratonTableRouteWithChildren
  '/season/$year': typeof LayoutSeasonYearRouteWithChildren
  '/team/$teamId': typeof LayoutTeamTeamIdRouteWithChildren
  '/teams/compare': typeof LayoutTeamsCompareRoute
  '/teams/map': typeof LayoutTeamsMapRoute
  '/teams/selection': typeof LayoutTeamsSelectionRoute
  '/about': typeof LayoutAboutIndexRoute
  '/dashboard/': typeof LayoutDashboardIndexRoute
  '/login': typeof LayoutLoginIndexRoute
  '/search/': typeof LayoutSearchIndexRoute
  '/seasons': typeof LayoutSeasonsIndexRoute
  '/teams/': typeof LayoutTeamsIndexRoute
  '/unauthorized': typeof LayoutUnauthorizedIndexLazyRoute
  '/dashboard/games/$today': typeof LayoutDashboardGamesTodayRouteWithChildren
  '/dashboard/season/$seasonId': typeof LayoutDashboardSeasonSeasonIdRouteWithChildren
  '/dashboard/team/$teamId': typeof LayoutDashboardTeamTeamIdRoute
  '/dashboard/teams/add': typeof LayoutDashboardTeamsAddRoute
  '/maraton/records/conceded': typeof LayoutMaratonRecordsConcededRoute
  '/maraton/records/points': typeof LayoutMaratonRecordsPointsRoute
  '/maraton/records/scored': typeof LayoutMaratonRecordsScoredRoute
  '/maraton/records/stats': typeof LayoutMaratonRecordsStatsRoute
  '/maraton/records/streaks': typeof LayoutMaratonRecordsStreaksRoute
  '/maraton/table/$maratonTable': typeof LayoutMaratonTableMaratonTableRoute
  '/season/$year/playoff': typeof LayoutSeasonYearPlayoffRouteWithChildren
  '/team/$teamId/$seasonId': typeof LayoutTeamTeamIdSeasonIdRoute
  '/team/$teamId/seasons': typeof LayoutTeamTeamIdSeasonsRoute
  '/dashboard/seasons': typeof LayoutDashboardSeasonsIndexRoute
  '/dashboard/teams': typeof LayoutDashboardTeamsIndexRoute
  '/team/$teamId/': typeof LayoutTeamTeamIdIndexRoute
  '/dashboard/games/$today/$gameId': typeof LayoutDashboardGamesTodayGameIdRouteWithChildren
  '/season/$year/$group/development': typeof LayoutSeasonYearGroupDevelopmentRoute
  '/season/$year/$group/games': typeof LayoutSeasonYearGroupGamesRoute
  '/season/$year/$group/interval': typeof LayoutSeasonYearGroupIntervalRoute
  '/season/$year/$group/map': typeof LayoutSeasonYearGroupMapRoute
  '/season/$year/$group/stats': typeof LayoutSeasonYearGroupStatsRoute
  '/season/$year/$group/tables': typeof LayoutSeasonYearGroupTablesRouteWithChildren
  '/season/$year/playoff/games': typeof LayoutSeasonYearPlayoffGamesRoute
  '/season/$year/playoff/map': typeof LayoutSeasonYearPlayoffMapRoute
  '/season/$year/playoff/stats': typeof LayoutSeasonYearPlayoffStatsRoute
  '/season/$year/playoff/table': typeof LayoutSeasonYearPlayoffTableRoute
  '/season/$year/$group': typeof LayoutSeasonYearGroupIndexRoute
  '/dashboard/games/$today/$gameId/date': typeof LayoutDashboardGamesTodayGameIdDateRoute
  '/dashboard/games/$today/$gameId/result': typeof LayoutDashboardGamesTodayGameIdResultRoute
  '/dashboard/season/$seasonId/$serieId/$serieId': typeof LayoutDashboardSeasonSeasonIdSerieIdSerieIdRoute
  '/season/$year/$group/tables/$table': typeof LayoutSeasonYearGroupTablesTableRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/maraton/table': typeof LayoutMaratonTableRouteWithChildren
  '/season/$year': typeof LayoutSeasonYearRouteWithChildren
  '/teams/compare': typeof LayoutTeamsCompareRoute
  '/teams/map': typeof LayoutTeamsMapRoute
  '/teams/selection': typeof LayoutTeamsSelectionRoute
  '/about': typeof LayoutAboutIndexRoute
  '/dashboard': typeof LayoutDashboardIndexRoute
  '/login': typeof LayoutLoginIndexRoute
  '/search': typeof LayoutSearchIndexRoute
  '/seasons': typeof LayoutSeasonsIndexRoute
  '/teams': typeof LayoutTeamsIndexRoute
  '/unauthorized': typeof LayoutUnauthorizedIndexLazyRoute
  '/dashboard/games/$today': typeof LayoutDashboardGamesTodayRouteWithChildren
  '/dashboard/season/$seasonId': typeof LayoutDashboardSeasonSeasonIdRouteWithChildren
  '/dashboard/team/$teamId': typeof LayoutDashboardTeamTeamIdRoute
  '/dashboard/teams/add': typeof LayoutDashboardTeamsAddRoute
  '/maraton/records/conceded': typeof LayoutMaratonRecordsConcededRoute
  '/maraton/records/points': typeof LayoutMaratonRecordsPointsRoute
  '/maraton/records/scored': typeof LayoutMaratonRecordsScoredRoute
  '/maraton/records/stats': typeof LayoutMaratonRecordsStatsRoute
  '/maraton/records/streaks': typeof LayoutMaratonRecordsStreaksRoute
  '/maraton/table/$maratonTable': typeof LayoutMaratonTableMaratonTableRoute
  '/season/$year/playoff': typeof LayoutSeasonYearPlayoffRouteWithChildren
  '/team/$teamId/$seasonId': typeof LayoutTeamTeamIdSeasonIdRoute
  '/team/$teamId/seasons': typeof LayoutTeamTeamIdSeasonsRoute
  '/dashboard/seasons': typeof LayoutDashboardSeasonsIndexRoute
  '/dashboard/teams': typeof LayoutDashboardTeamsIndexRoute
  '/team/$teamId': typeof LayoutTeamTeamIdIndexRoute
  '/dashboard/games/$today/$gameId': typeof LayoutDashboardGamesTodayGameIdRouteWithChildren
  '/season/$year/$group/development': typeof LayoutSeasonYearGroupDevelopmentRoute
  '/season/$year/$group/games': typeof LayoutSeasonYearGroupGamesRoute
  '/season/$year/$group/interval': typeof LayoutSeasonYearGroupIntervalRoute
  '/season/$year/$group/map': typeof LayoutSeasonYearGroupMapRoute
  '/season/$year/$group/stats': typeof LayoutSeasonYearGroupStatsRoute
  '/season/$year/$group/tables': typeof LayoutSeasonYearGroupTablesRouteWithChildren
  '/season/$year/playoff/games': typeof LayoutSeasonYearPlayoffGamesRoute
  '/season/$year/playoff/map': typeof LayoutSeasonYearPlayoffMapRoute
  '/season/$year/playoff/stats': typeof LayoutSeasonYearPlayoffStatsRoute
  '/season/$year/playoff/table': typeof LayoutSeasonYearPlayoffTableRoute
  '/season/$year/$group': typeof LayoutSeasonYearGroupIndexRoute
  '/dashboard/games/$today/$gameId/date': typeof LayoutDashboardGamesTodayGameIdDateRoute
  '/dashboard/games/$today/$gameId/result': typeof LayoutDashboardGamesTodayGameIdResultRoute
  '/dashboard/season/$seasonId/$serieId/$serieId': typeof LayoutDashboardSeasonSeasonIdSerieIdSerieIdRoute
  '/season/$year/$group/tables/$table': typeof LayoutSeasonYearGroupTablesTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/dashboard': typeof LayoutDashboardRouteWithChildren
  '/_layout/search': typeof LayoutSearchRouteWithChildren
  '/_layout/teams': typeof LayoutTeamsRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/maraton/table': typeof LayoutMaratonTableRouteWithChildren
  '/_layout/season/$year': typeof LayoutSeasonYearRouteWithChildren
  '/_layout/team/$teamId': typeof LayoutTeamTeamIdRouteWithChildren
  '/_layout/teams/compare': typeof LayoutTeamsCompareRoute
  '/_layout/teams/map': typeof LayoutTeamsMapRoute
  '/_layout/teams/selection': typeof LayoutTeamsSelectionRoute
  '/_layout/about/': typeof LayoutAboutIndexRoute
  '/_layout/dashboard/': typeof LayoutDashboardIndexRoute
  '/_layout/login/': typeof LayoutLoginIndexRoute
  '/_layout/search/': typeof LayoutSearchIndexRoute
  '/_layout/seasons/': typeof LayoutSeasonsIndexRoute
  '/_layout/teams/': typeof LayoutTeamsIndexRoute
  '/_layout/unauthorized/': typeof LayoutUnauthorizedIndexLazyRoute
  '/_layout/dashboard/games/$today': typeof LayoutDashboardGamesTodayRouteWithChildren
  '/_layout/dashboard/season/$seasonId': typeof LayoutDashboardSeasonSeasonIdRouteWithChildren
  '/_layout/dashboard/team/$teamId': typeof LayoutDashboardTeamTeamIdRoute
  '/_layout/dashboard/teams/add': typeof LayoutDashboardTeamsAddRoute
  '/_layout/maraton/records/conceded': typeof LayoutMaratonRecordsConcededRoute
  '/_layout/maraton/records/points': typeof LayoutMaratonRecordsPointsRoute
  '/_layout/maraton/records/scored': typeof LayoutMaratonRecordsScoredRoute
  '/_layout/maraton/records/stats': typeof LayoutMaratonRecordsStatsRoute
  '/_layout/maraton/records/streaks': typeof LayoutMaratonRecordsStreaksRoute
  '/_layout/maraton/table/$maratonTable': typeof LayoutMaratonTableMaratonTableRoute
  '/_layout/season/$year/playoff': typeof LayoutSeasonYearPlayoffRouteWithChildren
  '/_layout/team/$teamId/$seasonId': typeof LayoutTeamTeamIdSeasonIdRoute
  '/_layout/team/$teamId/seasons': typeof LayoutTeamTeamIdSeasonsRoute
  '/_layout/dashboard/seasons/': typeof LayoutDashboardSeasonsIndexRoute
  '/_layout/dashboard/teams/': typeof LayoutDashboardTeamsIndexRoute
  '/_layout/team/$teamId/': typeof LayoutTeamTeamIdIndexRoute
  '/_layout/dashboard/games/$today/$gameId': typeof LayoutDashboardGamesTodayGameIdRouteWithChildren
  '/_layout/season/$year/$group/development': typeof LayoutSeasonYearGroupDevelopmentRoute
  '/_layout/season/$year/$group/games': typeof LayoutSeasonYearGroupGamesRoute
  '/_layout/season/$year/$group/interval': typeof LayoutSeasonYearGroupIntervalRoute
  '/_layout/season/$year/$group/map': typeof LayoutSeasonYearGroupMapRoute
  '/_layout/season/$year/$group/stats': typeof LayoutSeasonYearGroupStatsRoute
  '/_layout/season/$year/$group/tables': typeof LayoutSeasonYearGroupTablesRouteWithChildren
  '/_layout/season/$year/playoff/games': typeof LayoutSeasonYearPlayoffGamesRoute
  '/_layout/season/$year/playoff/map': typeof LayoutSeasonYearPlayoffMapRoute
  '/_layout/season/$year/playoff/stats': typeof LayoutSeasonYearPlayoffStatsRoute
  '/_layout/season/$year/playoff/table': typeof LayoutSeasonYearPlayoffTableRoute
  '/_layout/season/$year/$group/': typeof LayoutSeasonYearGroupIndexRoute
  '/_layout/dashboard/games/$today/$gameId/date': typeof LayoutDashboardGamesTodayGameIdDateRoute
  '/_layout/dashboard/games/$today/$gameId/result': typeof LayoutDashboardGamesTodayGameIdResultRoute
  '/_layout/dashboard/season/$seasonId/$serieId/$serieId': typeof LayoutDashboardSeasonSeasonIdSerieIdSerieIdRoute
  '/_layout/season/$year/$group/tables/$table': typeof LayoutSeasonYearGroupTablesTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/search'
    | '/teams'
    | '/'
    | '/maraton/table'
    | '/season/$year'
    | '/team/$teamId'
    | '/teams/compare'
    | '/teams/map'
    | '/teams/selection'
    | '/about'
    | '/dashboard/'
    | '/login'
    | '/search/'
    | '/seasons'
    | '/teams/'
    | '/unauthorized'
    | '/dashboard/games/$today'
    | '/dashboard/season/$seasonId'
    | '/dashboard/team/$teamId'
    | '/dashboard/teams/add'
    | '/maraton/records/conceded'
    | '/maraton/records/points'
    | '/maraton/records/scored'
    | '/maraton/records/stats'
    | '/maraton/records/streaks'
    | '/maraton/table/$maratonTable'
    | '/season/$year/playoff'
    | '/team/$teamId/$seasonId'
    | '/team/$teamId/seasons'
    | '/dashboard/seasons'
    | '/dashboard/teams'
    | '/team/$teamId/'
    | '/dashboard/games/$today/$gameId'
    | '/season/$year/$group/development'
    | '/season/$year/$group/games'
    | '/season/$year/$group/interval'
    | '/season/$year/$group/map'
    | '/season/$year/$group/stats'
    | '/season/$year/$group/tables'
    | '/season/$year/playoff/games'
    | '/season/$year/playoff/map'
    | '/season/$year/playoff/stats'
    | '/season/$year/playoff/table'
    | '/season/$year/$group'
    | '/dashboard/games/$today/$gameId/date'
    | '/dashboard/games/$today/$gameId/result'
    | '/dashboard/season/$seasonId/$serieId/$serieId'
    | '/season/$year/$group/tables/$table'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/maraton/table'
    | '/season/$year'
    | '/teams/compare'
    | '/teams/map'
    | '/teams/selection'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/search'
    | '/seasons'
    | '/teams'
    | '/unauthorized'
    | '/dashboard/games/$today'
    | '/dashboard/season/$seasonId'
    | '/dashboard/team/$teamId'
    | '/dashboard/teams/add'
    | '/maraton/records/conceded'
    | '/maraton/records/points'
    | '/maraton/records/scored'
    | '/maraton/records/stats'
    | '/maraton/records/streaks'
    | '/maraton/table/$maratonTable'
    | '/season/$year/playoff'
    | '/team/$teamId/$seasonId'
    | '/team/$teamId/seasons'
    | '/dashboard/seasons'
    | '/dashboard/teams'
    | '/team/$teamId'
    | '/dashboard/games/$today/$gameId'
    | '/season/$year/$group/development'
    | '/season/$year/$group/games'
    | '/season/$year/$group/interval'
    | '/season/$year/$group/map'
    | '/season/$year/$group/stats'
    | '/season/$year/$group/tables'
    | '/season/$year/playoff/games'
    | '/season/$year/playoff/map'
    | '/season/$year/playoff/stats'
    | '/season/$year/playoff/table'
    | '/season/$year/$group'
    | '/dashboard/games/$today/$gameId/date'
    | '/dashboard/games/$today/$gameId/result'
    | '/dashboard/season/$seasonId/$serieId/$serieId'
    | '/season/$year/$group/tables/$table'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/dashboard'
    | '/_layout/search'
    | '/_layout/teams'
    | '/_layout/'
    | '/_layout/maraton/table'
    | '/_layout/season/$year'
    | '/_layout/team/$teamId'
    | '/_layout/teams/compare'
    | '/_layout/teams/map'
    | '/_layout/teams/selection'
    | '/_layout/about/'
    | '/_layout/dashboard/'
    | '/_layout/login/'
    | '/_layout/search/'
    | '/_layout/seasons/'
    | '/_layout/teams/'
    | '/_layout/unauthorized/'
    | '/_layout/dashboard/games/$today'
    | '/_layout/dashboard/season/$seasonId'
    | '/_layout/dashboard/team/$teamId'
    | '/_layout/dashboard/teams/add'
    | '/_layout/maraton/records/conceded'
    | '/_layout/maraton/records/points'
    | '/_layout/maraton/records/scored'
    | '/_layout/maraton/records/stats'
    | '/_layout/maraton/records/streaks'
    | '/_layout/maraton/table/$maratonTable'
    | '/_layout/season/$year/playoff'
    | '/_layout/team/$teamId/$seasonId'
    | '/_layout/team/$teamId/seasons'
    | '/_layout/dashboard/seasons/'
    | '/_layout/dashboard/teams/'
    | '/_layout/team/$teamId/'
    | '/_layout/dashboard/games/$today/$gameId'
    | '/_layout/season/$year/$group/development'
    | '/_layout/season/$year/$group/games'
    | '/_layout/season/$year/$group/interval'
    | '/_layout/season/$year/$group/map'
    | '/_layout/season/$year/$group/stats'
    | '/_layout/season/$year/$group/tables'
    | '/_layout/season/$year/playoff/games'
    | '/_layout/season/$year/playoff/map'
    | '/_layout/season/$year/playoff/stats'
    | '/_layout/season/$year/playoff/table'
    | '/_layout/season/$year/$group/'
    | '/_layout/dashboard/games/$today/$gameId/date'
    | '/_layout/dashboard/games/$today/$gameId/result'
    | '/_layout/dashboard/season/$seasonId/$serieId/$serieId'
    | '/_layout/season/$year/$group/tables/$table'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/teams': {
      id: '/_layout/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof LayoutTeamsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/search': {
      id: '/_layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutSearchRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/unauthorized/': {
      id: '/_layout/unauthorized/'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof LayoutUnauthorizedIndexLazyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/teams/': {
      id: '/_layout/teams/'
      path: '/'
      fullPath: '/teams/'
      preLoaderRoute: typeof LayoutTeamsIndexRouteImport
      parentRoute: typeof LayoutTeamsRoute
    }
    '/_layout/seasons/': {
      id: '/_layout/seasons/'
      path: '/seasons'
      fullPath: '/seasons'
      preLoaderRoute: typeof LayoutSeasonsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/search/': {
      id: '/_layout/search/'
      path: '/'
      fullPath: '/search/'
      preLoaderRoute: typeof LayoutSearchIndexRouteImport
      parentRoute: typeof LayoutSearchRoute
    }
    '/_layout/login/': {
      id: '/_layout/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutLoginIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard/': {
      id: '/_layout/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof LayoutDashboardIndexRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout/about/': {
      id: '/_layout/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/teams/selection': {
      id: '/_layout/teams/selection'
      path: '/selection'
      fullPath: '/teams/selection'
      preLoaderRoute: typeof LayoutTeamsSelectionRouteImport
      parentRoute: typeof LayoutTeamsRoute
    }
    '/_layout/teams/map': {
      id: '/_layout/teams/map'
      path: '/map'
      fullPath: '/teams/map'
      preLoaderRoute: typeof LayoutTeamsMapRouteImport
      parentRoute: typeof LayoutTeamsRoute
    }
    '/_layout/teams/compare': {
      id: '/_layout/teams/compare'
      path: '/compare'
      fullPath: '/teams/compare'
      preLoaderRoute: typeof LayoutTeamsCompareRouteImport
      parentRoute: typeof LayoutTeamsRoute
    }
    '/_layout/team/$teamId': {
      id: '/_layout/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/team/$teamId'
      preLoaderRoute: typeof LayoutTeamTeamIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/season/$year': {
      id: '/_layout/season/$year'
      path: '/season/$year'
      fullPath: '/season/$year'
      preLoaderRoute: typeof LayoutSeasonYearRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/maraton/table': {
      id: '/_layout/maraton/table'
      path: '/maraton/table'
      fullPath: '/maraton/table'
      preLoaderRoute: typeof LayoutMaratonTableRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/team/$teamId/': {
      id: '/_layout/team/$teamId/'
      path: '/'
      fullPath: '/team/$teamId/'
      preLoaderRoute: typeof LayoutTeamTeamIdIndexRouteImport
      parentRoute: typeof LayoutTeamTeamIdRoute
    }
    '/_layout/dashboard/teams/': {
      id: '/_layout/dashboard/teams/'
      path: '/teams'
      fullPath: '/dashboard/teams'
      preLoaderRoute: typeof LayoutDashboardTeamsIndexRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout/dashboard/seasons/': {
      id: '/_layout/dashboard/seasons/'
      path: '/seasons'
      fullPath: '/dashboard/seasons'
      preLoaderRoute: typeof LayoutDashboardSeasonsIndexRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout/team/$teamId/seasons': {
      id: '/_layout/team/$teamId/seasons'
      path: '/seasons'
      fullPath: '/team/$teamId/seasons'
      preLoaderRoute: typeof LayoutTeamTeamIdSeasonsRouteImport
      parentRoute: typeof LayoutTeamTeamIdRoute
    }
    '/_layout/team/$teamId/$seasonId': {
      id: '/_layout/team/$teamId/$seasonId'
      path: '/$seasonId'
      fullPath: '/team/$teamId/$seasonId'
      preLoaderRoute: typeof LayoutTeamTeamIdSeasonIdRouteImport
      parentRoute: typeof LayoutTeamTeamIdRoute
    }
    '/_layout/season/$year/playoff': {
      id: '/_layout/season/$year/playoff'
      path: '/playoff'
      fullPath: '/season/$year/playoff'
      preLoaderRoute: typeof LayoutSeasonYearPlayoffRouteImport
      parentRoute: typeof LayoutSeasonYearRoute
    }
    '/_layout/maraton/table/$maratonTable': {
      id: '/_layout/maraton/table/$maratonTable'
      path: '/$maratonTable'
      fullPath: '/maraton/table/$maratonTable'
      preLoaderRoute: typeof LayoutMaratonTableMaratonTableRouteImport
      parentRoute: typeof LayoutMaratonTableRoute
    }
    '/_layout/maraton/records/streaks': {
      id: '/_layout/maraton/records/streaks'
      path: '/maraton/records/streaks'
      fullPath: '/maraton/records/streaks'
      preLoaderRoute: typeof LayoutMaratonRecordsStreaksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/maraton/records/stats': {
      id: '/_layout/maraton/records/stats'
      path: '/maraton/records/stats'
      fullPath: '/maraton/records/stats'
      preLoaderRoute: typeof LayoutMaratonRecordsStatsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/maraton/records/scored': {
      id: '/_layout/maraton/records/scored'
      path: '/maraton/records/scored'
      fullPath: '/maraton/records/scored'
      preLoaderRoute: typeof LayoutMaratonRecordsScoredRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/maraton/records/points': {
      id: '/_layout/maraton/records/points'
      path: '/maraton/records/points'
      fullPath: '/maraton/records/points'
      preLoaderRoute: typeof LayoutMaratonRecordsPointsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/maraton/records/conceded': {
      id: '/_layout/maraton/records/conceded'
      path: '/maraton/records/conceded'
      fullPath: '/maraton/records/conceded'
      preLoaderRoute: typeof LayoutMaratonRecordsConcededRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard/teams/add': {
      id: '/_layout/dashboard/teams/add'
      path: '/teams/add'
      fullPath: '/dashboard/teams/add'
      preLoaderRoute: typeof LayoutDashboardTeamsAddRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout/dashboard/team/$teamId': {
      id: '/_layout/dashboard/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/dashboard/team/$teamId'
      preLoaderRoute: typeof LayoutDashboardTeamTeamIdRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout/dashboard/season/$seasonId': {
      id: '/_layout/dashboard/season/$seasonId'
      path: '/season/$seasonId'
      fullPath: '/dashboard/season/$seasonId'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout/dashboard/games/$today': {
      id: '/_layout/dashboard/games/$today'
      path: '/games/$today'
      fullPath: '/dashboard/games/$today'
      preLoaderRoute: typeof LayoutDashboardGamesTodayRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout/season/$year/$group/': {
      id: '/_layout/season/$year/$group/'
      path: '/$group'
      fullPath: '/season/$year/$group'
      preLoaderRoute: typeof LayoutSeasonYearGroupIndexRouteImport
      parentRoute: typeof LayoutSeasonYearRoute
    }
    '/_layout/season/$year/playoff/table': {
      id: '/_layout/season/$year/playoff/table'
      path: '/table'
      fullPath: '/season/$year/playoff/table'
      preLoaderRoute: typeof LayoutSeasonYearPlayoffTableRouteImport
      parentRoute: typeof LayoutSeasonYearPlayoffRoute
    }
    '/_layout/season/$year/playoff/stats': {
      id: '/_layout/season/$year/playoff/stats'
      path: '/stats'
      fullPath: '/season/$year/playoff/stats'
      preLoaderRoute: typeof LayoutSeasonYearPlayoffStatsRouteImport
      parentRoute: typeof LayoutSeasonYearPlayoffRoute
    }
    '/_layout/season/$year/playoff/map': {
      id: '/_layout/season/$year/playoff/map'
      path: '/map'
      fullPath: '/season/$year/playoff/map'
      preLoaderRoute: typeof LayoutSeasonYearPlayoffMapRouteImport
      parentRoute: typeof LayoutSeasonYearPlayoffRoute
    }
    '/_layout/season/$year/playoff/games': {
      id: '/_layout/season/$year/playoff/games'
      path: '/games'
      fullPath: '/season/$year/playoff/games'
      preLoaderRoute: typeof LayoutSeasonYearPlayoffGamesRouteImport
      parentRoute: typeof LayoutSeasonYearPlayoffRoute
    }
    '/_layout/season/$year/$group/tables': {
      id: '/_layout/season/$year/$group/tables'
      path: '/$group/tables'
      fullPath: '/season/$year/$group/tables'
      preLoaderRoute: typeof LayoutSeasonYearGroupTablesRouteImport
      parentRoute: typeof LayoutSeasonYearRoute
    }
    '/_layout/season/$year/$group/stats': {
      id: '/_layout/season/$year/$group/stats'
      path: '/$group/stats'
      fullPath: '/season/$year/$group/stats'
      preLoaderRoute: typeof LayoutSeasonYearGroupStatsRouteImport
      parentRoute: typeof LayoutSeasonYearRoute
    }
    '/_layout/season/$year/$group/map': {
      id: '/_layout/season/$year/$group/map'
      path: '/$group/map'
      fullPath: '/season/$year/$group/map'
      preLoaderRoute: typeof LayoutSeasonYearGroupMapRouteImport
      parentRoute: typeof LayoutSeasonYearRoute
    }
    '/_layout/season/$year/$group/interval': {
      id: '/_layout/season/$year/$group/interval'
      path: '/$group/interval'
      fullPath: '/season/$year/$group/interval'
      preLoaderRoute: typeof LayoutSeasonYearGroupIntervalRouteImport
      parentRoute: typeof LayoutSeasonYearRoute
    }
    '/_layout/season/$year/$group/games': {
      id: '/_layout/season/$year/$group/games'
      path: '/$group/games'
      fullPath: '/season/$year/$group/games'
      preLoaderRoute: typeof LayoutSeasonYearGroupGamesRouteImport
      parentRoute: typeof LayoutSeasonYearRoute
    }
    '/_layout/season/$year/$group/development': {
      id: '/_layout/season/$year/$group/development'
      path: '/$group/development'
      fullPath: '/season/$year/$group/development'
      preLoaderRoute: typeof LayoutSeasonYearGroupDevelopmentRouteImport
      parentRoute: typeof LayoutSeasonYearRoute
    }
    '/_layout/dashboard/games/$today/$gameId': {
      id: '/_layout/dashboard/games/$today/$gameId'
      path: '/$gameId'
      fullPath: '/dashboard/games/$today/$gameId'
      preLoaderRoute: typeof LayoutDashboardGamesTodayGameIdRouteImport
      parentRoute: typeof LayoutDashboardGamesTodayRoute
    }
    '/_layout/season/$year/$group/tables/$table': {
      id: '/_layout/season/$year/$group/tables/$table'
      path: '/$table'
      fullPath: '/season/$year/$group/tables/$table'
      preLoaderRoute: typeof LayoutSeasonYearGroupTablesTableRouteImport
      parentRoute: typeof LayoutSeasonYearGroupTablesRoute
    }
    '/_layout/dashboard/season/$seasonId/$serieId/$serieId': {
      id: '/_layout/dashboard/season/$seasonId/$serieId/$serieId'
      path: '/$serieId/$serieId'
      fullPath: '/dashboard/season/$seasonId/$serieId/$serieId'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdSerieIdSerieIdRouteImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdRoute
    }
    '/_layout/dashboard/games/$today/$gameId/result': {
      id: '/_layout/dashboard/games/$today/$gameId/result'
      path: '/result'
      fullPath: '/dashboard/games/$today/$gameId/result'
      preLoaderRoute: typeof LayoutDashboardGamesTodayGameIdResultRouteImport
      parentRoute: typeof LayoutDashboardGamesTodayGameIdRoute
    }
    '/_layout/dashboard/games/$today/$gameId/date': {
      id: '/_layout/dashboard/games/$today/$gameId/date'
      path: '/date'
      fullPath: '/dashboard/games/$today/$gameId/date'
      preLoaderRoute: typeof LayoutDashboardGamesTodayGameIdDateRouteImport
      parentRoute: typeof LayoutDashboardGamesTodayGameIdRoute
    }
  }
}

interface LayoutDashboardGamesTodayGameIdRouteChildren {
  LayoutDashboardGamesTodayGameIdDateRoute: typeof LayoutDashboardGamesTodayGameIdDateRoute
  LayoutDashboardGamesTodayGameIdResultRoute: typeof LayoutDashboardGamesTodayGameIdResultRoute
}

const LayoutDashboardGamesTodayGameIdRouteChildren: LayoutDashboardGamesTodayGameIdRouteChildren =
  {
    LayoutDashboardGamesTodayGameIdDateRoute:
      LayoutDashboardGamesTodayGameIdDateRoute,
    LayoutDashboardGamesTodayGameIdResultRoute:
      LayoutDashboardGamesTodayGameIdResultRoute,
  }

const LayoutDashboardGamesTodayGameIdRouteWithChildren =
  LayoutDashboardGamesTodayGameIdRoute._addFileChildren(
    LayoutDashboardGamesTodayGameIdRouteChildren,
  )

interface LayoutDashboardGamesTodayRouteChildren {
  LayoutDashboardGamesTodayGameIdRoute: typeof LayoutDashboardGamesTodayGameIdRouteWithChildren
}

const LayoutDashboardGamesTodayRouteChildren: LayoutDashboardGamesTodayRouteChildren =
  {
    LayoutDashboardGamesTodayGameIdRoute:
      LayoutDashboardGamesTodayGameIdRouteWithChildren,
  }

const LayoutDashboardGamesTodayRouteWithChildren =
  LayoutDashboardGamesTodayRoute._addFileChildren(
    LayoutDashboardGamesTodayRouteChildren,
  )

interface LayoutDashboardSeasonSeasonIdRouteChildren {
  LayoutDashboardSeasonSeasonIdSerieIdSerieIdRoute: typeof LayoutDashboardSeasonSeasonIdSerieIdSerieIdRoute
}

const LayoutDashboardSeasonSeasonIdRouteChildren: LayoutDashboardSeasonSeasonIdRouteChildren =
  {
    LayoutDashboardSeasonSeasonIdSerieIdSerieIdRoute:
      LayoutDashboardSeasonSeasonIdSerieIdSerieIdRoute,
  }

const LayoutDashboardSeasonSeasonIdRouteWithChildren =
  LayoutDashboardSeasonSeasonIdRoute._addFileChildren(
    LayoutDashboardSeasonSeasonIdRouteChildren,
  )

interface LayoutDashboardRouteChildren {
  LayoutDashboardIndexRoute: typeof LayoutDashboardIndexRoute
  LayoutDashboardGamesTodayRoute: typeof LayoutDashboardGamesTodayRouteWithChildren
  LayoutDashboardSeasonSeasonIdRoute: typeof LayoutDashboardSeasonSeasonIdRouteWithChildren
  LayoutDashboardTeamTeamIdRoute: typeof LayoutDashboardTeamTeamIdRoute
  LayoutDashboardTeamsAddRoute: typeof LayoutDashboardTeamsAddRoute
  LayoutDashboardSeasonsIndexRoute: typeof LayoutDashboardSeasonsIndexRoute
  LayoutDashboardTeamsIndexRoute: typeof LayoutDashboardTeamsIndexRoute
}

const LayoutDashboardRouteChildren: LayoutDashboardRouteChildren = {
  LayoutDashboardIndexRoute: LayoutDashboardIndexRoute,
  LayoutDashboardGamesTodayRoute: LayoutDashboardGamesTodayRouteWithChildren,
  LayoutDashboardSeasonSeasonIdRoute:
    LayoutDashboardSeasonSeasonIdRouteWithChildren,
  LayoutDashboardTeamTeamIdRoute: LayoutDashboardTeamTeamIdRoute,
  LayoutDashboardTeamsAddRoute: LayoutDashboardTeamsAddRoute,
  LayoutDashboardSeasonsIndexRoute: LayoutDashboardSeasonsIndexRoute,
  LayoutDashboardTeamsIndexRoute: LayoutDashboardTeamsIndexRoute,
}

const LayoutDashboardRouteWithChildren = LayoutDashboardRoute._addFileChildren(
  LayoutDashboardRouteChildren,
)

interface LayoutSearchRouteChildren {
  LayoutSearchIndexRoute: typeof LayoutSearchIndexRoute
}

const LayoutSearchRouteChildren: LayoutSearchRouteChildren = {
  LayoutSearchIndexRoute: LayoutSearchIndexRoute,
}

const LayoutSearchRouteWithChildren = LayoutSearchRoute._addFileChildren(
  LayoutSearchRouteChildren,
)

interface LayoutTeamsRouteChildren {
  LayoutTeamsCompareRoute: typeof LayoutTeamsCompareRoute
  LayoutTeamsMapRoute: typeof LayoutTeamsMapRoute
  LayoutTeamsSelectionRoute: typeof LayoutTeamsSelectionRoute
  LayoutTeamsIndexRoute: typeof LayoutTeamsIndexRoute
}

const LayoutTeamsRouteChildren: LayoutTeamsRouteChildren = {
  LayoutTeamsCompareRoute: LayoutTeamsCompareRoute,
  LayoutTeamsMapRoute: LayoutTeamsMapRoute,
  LayoutTeamsSelectionRoute: LayoutTeamsSelectionRoute,
  LayoutTeamsIndexRoute: LayoutTeamsIndexRoute,
}

const LayoutTeamsRouteWithChildren = LayoutTeamsRoute._addFileChildren(
  LayoutTeamsRouteChildren,
)

interface LayoutMaratonTableRouteChildren {
  LayoutMaratonTableMaratonTableRoute: typeof LayoutMaratonTableMaratonTableRoute
}

const LayoutMaratonTableRouteChildren: LayoutMaratonTableRouteChildren = {
  LayoutMaratonTableMaratonTableRoute: LayoutMaratonTableMaratonTableRoute,
}

const LayoutMaratonTableRouteWithChildren =
  LayoutMaratonTableRoute._addFileChildren(LayoutMaratonTableRouteChildren)

interface LayoutSeasonYearPlayoffRouteChildren {
  LayoutSeasonYearPlayoffGamesRoute: typeof LayoutSeasonYearPlayoffGamesRoute
  LayoutSeasonYearPlayoffMapRoute: typeof LayoutSeasonYearPlayoffMapRoute
  LayoutSeasonYearPlayoffStatsRoute: typeof LayoutSeasonYearPlayoffStatsRoute
  LayoutSeasonYearPlayoffTableRoute: typeof LayoutSeasonYearPlayoffTableRoute
}

const LayoutSeasonYearPlayoffRouteChildren: LayoutSeasonYearPlayoffRouteChildren =
  {
    LayoutSeasonYearPlayoffGamesRoute: LayoutSeasonYearPlayoffGamesRoute,
    LayoutSeasonYearPlayoffMapRoute: LayoutSeasonYearPlayoffMapRoute,
    LayoutSeasonYearPlayoffStatsRoute: LayoutSeasonYearPlayoffStatsRoute,
    LayoutSeasonYearPlayoffTableRoute: LayoutSeasonYearPlayoffTableRoute,
  }

const LayoutSeasonYearPlayoffRouteWithChildren =
  LayoutSeasonYearPlayoffRoute._addFileChildren(
    LayoutSeasonYearPlayoffRouteChildren,
  )

interface LayoutSeasonYearGroupTablesRouteChildren {
  LayoutSeasonYearGroupTablesTableRoute: typeof LayoutSeasonYearGroupTablesTableRoute
}

const LayoutSeasonYearGroupTablesRouteChildren: LayoutSeasonYearGroupTablesRouteChildren =
  {
    LayoutSeasonYearGroupTablesTableRoute:
      LayoutSeasonYearGroupTablesTableRoute,
  }

const LayoutSeasonYearGroupTablesRouteWithChildren =
  LayoutSeasonYearGroupTablesRoute._addFileChildren(
    LayoutSeasonYearGroupTablesRouteChildren,
  )

interface LayoutSeasonYearRouteChildren {
  LayoutSeasonYearPlayoffRoute: typeof LayoutSeasonYearPlayoffRouteWithChildren
  LayoutSeasonYearGroupDevelopmentRoute: typeof LayoutSeasonYearGroupDevelopmentRoute
  LayoutSeasonYearGroupGamesRoute: typeof LayoutSeasonYearGroupGamesRoute
  LayoutSeasonYearGroupIntervalRoute: typeof LayoutSeasonYearGroupIntervalRoute
  LayoutSeasonYearGroupMapRoute: typeof LayoutSeasonYearGroupMapRoute
  LayoutSeasonYearGroupStatsRoute: typeof LayoutSeasonYearGroupStatsRoute
  LayoutSeasonYearGroupTablesRoute: typeof LayoutSeasonYearGroupTablesRouteWithChildren
  LayoutSeasonYearGroupIndexRoute: typeof LayoutSeasonYearGroupIndexRoute
}

const LayoutSeasonYearRouteChildren: LayoutSeasonYearRouteChildren = {
  LayoutSeasonYearPlayoffRoute: LayoutSeasonYearPlayoffRouteWithChildren,
  LayoutSeasonYearGroupDevelopmentRoute: LayoutSeasonYearGroupDevelopmentRoute,
  LayoutSeasonYearGroupGamesRoute: LayoutSeasonYearGroupGamesRoute,
  LayoutSeasonYearGroupIntervalRoute: LayoutSeasonYearGroupIntervalRoute,
  LayoutSeasonYearGroupMapRoute: LayoutSeasonYearGroupMapRoute,
  LayoutSeasonYearGroupStatsRoute: LayoutSeasonYearGroupStatsRoute,
  LayoutSeasonYearGroupTablesRoute:
    LayoutSeasonYearGroupTablesRouteWithChildren,
  LayoutSeasonYearGroupIndexRoute: LayoutSeasonYearGroupIndexRoute,
}

const LayoutSeasonYearRouteWithChildren =
  LayoutSeasonYearRoute._addFileChildren(LayoutSeasonYearRouteChildren)

interface LayoutTeamTeamIdRouteChildren {
  LayoutTeamTeamIdSeasonIdRoute: typeof LayoutTeamTeamIdSeasonIdRoute
  LayoutTeamTeamIdSeasonsRoute: typeof LayoutTeamTeamIdSeasonsRoute
  LayoutTeamTeamIdIndexRoute: typeof LayoutTeamTeamIdIndexRoute
}

const LayoutTeamTeamIdRouteChildren: LayoutTeamTeamIdRouteChildren = {
  LayoutTeamTeamIdSeasonIdRoute: LayoutTeamTeamIdSeasonIdRoute,
  LayoutTeamTeamIdSeasonsRoute: LayoutTeamTeamIdSeasonsRoute,
  LayoutTeamTeamIdIndexRoute: LayoutTeamTeamIdIndexRoute,
}

const LayoutTeamTeamIdRouteWithChildren =
  LayoutTeamTeamIdRoute._addFileChildren(LayoutTeamTeamIdRouteChildren)

interface LayoutRouteChildren {
  LayoutDashboardRoute: typeof LayoutDashboardRouteWithChildren
  LayoutSearchRoute: typeof LayoutSearchRouteWithChildren
  LayoutTeamsRoute: typeof LayoutTeamsRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutMaratonTableRoute: typeof LayoutMaratonTableRouteWithChildren
  LayoutSeasonYearRoute: typeof LayoutSeasonYearRouteWithChildren
  LayoutTeamTeamIdRoute: typeof LayoutTeamTeamIdRouteWithChildren
  LayoutAboutIndexRoute: typeof LayoutAboutIndexRoute
  LayoutLoginIndexRoute: typeof LayoutLoginIndexRoute
  LayoutSeasonsIndexRoute: typeof LayoutSeasonsIndexRoute
  LayoutUnauthorizedIndexLazyRoute: typeof LayoutUnauthorizedIndexLazyRoute
  LayoutMaratonRecordsConcededRoute: typeof LayoutMaratonRecordsConcededRoute
  LayoutMaratonRecordsPointsRoute: typeof LayoutMaratonRecordsPointsRoute
  LayoutMaratonRecordsScoredRoute: typeof LayoutMaratonRecordsScoredRoute
  LayoutMaratonRecordsStatsRoute: typeof LayoutMaratonRecordsStatsRoute
  LayoutMaratonRecordsStreaksRoute: typeof LayoutMaratonRecordsStreaksRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDashboardRoute: LayoutDashboardRouteWithChildren,
  LayoutSearchRoute: LayoutSearchRouteWithChildren,
  LayoutTeamsRoute: LayoutTeamsRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutMaratonTableRoute: LayoutMaratonTableRouteWithChildren,
  LayoutSeasonYearRoute: LayoutSeasonYearRouteWithChildren,
  LayoutTeamTeamIdRoute: LayoutTeamTeamIdRouteWithChildren,
  LayoutAboutIndexRoute: LayoutAboutIndexRoute,
  LayoutLoginIndexRoute: LayoutLoginIndexRoute,
  LayoutSeasonsIndexRoute: LayoutSeasonsIndexRoute,
  LayoutUnauthorizedIndexLazyRoute: LayoutUnauthorizedIndexLazyRoute,
  LayoutMaratonRecordsConcededRoute: LayoutMaratonRecordsConcededRoute,
  LayoutMaratonRecordsPointsRoute: LayoutMaratonRecordsPointsRoute,
  LayoutMaratonRecordsScoredRoute: LayoutMaratonRecordsScoredRoute,
  LayoutMaratonRecordsStatsRoute: LayoutMaratonRecordsStatsRoute,
  LayoutMaratonRecordsStreaksRoute: LayoutMaratonRecordsStreaksRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
