/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTeamsRouteImport } from './routes/_layout/teams'
import { Route as LayoutSeasonsRouteImport } from './routes/_layout/seasons'
import { Route as LayoutSearchRouteImport } from './routes/_layout/search'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutUnauthorizedIndexRouteImport } from './routes/_layout/unauthorized/index'
import { Route as LayoutSeasonsIndexRouteImport } from './routes/_layout/seasons/index'
import { Route as LayoutSearchIndexRouteImport } from './routes/_layout/search/index'
import { Route as LayoutLogoutIndexRouteImport } from './routes/_layout/logout/index'
import { Route as LayoutLoginIndexRouteImport } from './routes/_layout/login/index'
import { Route as LayoutDashboardIndexRouteImport } from './routes/_layout/dashboard/index'
import { Route as LayoutAboutIndexRouteImport } from './routes/_layout/about/index'
import { Route as ApiV1HealthRouteImport } from './routes/api/v1/health'
import { Route as LayoutTeamsMapRouteImport } from './routes/_layout/teams/map'
import { Route as LayoutTeamsListRouteImport } from './routes/_layout/teams/list'
import { Route as LayoutTeamsCompareRouteImport } from './routes/_layout/teams/compare'
import { Route as LayoutTeamsTeamIdRouteImport } from './routes/_layout/teams/$teamId'
import { Route as LayoutSeasonsYearRouteImport } from './routes/_layout/seasons/$year'
import { Route as LayoutSearchHelpRouteImport } from './routes/_layout/search/help'
import { Route as LayoutMaratonTableRouteImport } from './routes/_layout/maraton/table'
import { Route as LayoutMaratonRecordsRouteImport } from './routes/_layout/maraton/records'
import { Route as LayoutAboutChangelogRouteImport } from './routes/_layout/about/changelog'
import { Route as LayoutMaratonHelpIndexRouteImport } from './routes/_layout/maraton/help/index'
import { Route as LayoutDashboardTeamsIndexRouteImport } from './routes/_layout/dashboard/teams/index'
import { Route as LayoutDashboardSeasonsIndexRouteImport } from './routes/_layout/dashboard/seasons/index'
import { Route as LayoutDashboardNewseasonIndexRouteImport } from './routes/_layout/dashboard/newseason/index'
import { Route as LayoutDashboardErrorIdIndexRouteImport } from './routes/_layout/dashboard/$errorId/index'
import { Route as LayoutTeamsTeamIdSeasonIdRouteImport } from './routes/_layout/teams/$teamId/$seasonId'
import { Route as LayoutSeasonsYearPlayoffRouteImport } from './routes/_layout/seasons/$year/playoff'
import { Route as LayoutSeasonsYearGroupRouteImport } from './routes/_layout/seasons/$year/$group'
import { Route as LayoutMaratonTableMaratonTableRouteImport } from './routes/_layout/maraton/table/$maratonTable'
import { Route as LayoutMaratonRecordsStreaksRouteImport } from './routes/_layout/maraton/records/streaks'
import { Route as LayoutMaratonRecordsStatsRouteImport } from './routes/_layout/maraton/records/stats'
import { Route as LayoutMaratonRecordsScoredRouteImport } from './routes/_layout/maraton/records/scored'
import { Route as LayoutMaratonRecordsPointsRouteImport } from './routes/_layout/maraton/records/points'
import { Route as LayoutMaratonRecordsConcededRouteImport } from './routes/_layout/maraton/records/conceded'
import { Route as LayoutDashboardTeamsAddRouteImport } from './routes/_layout/dashboard/teams/add'
import { Route as LayoutDashboardTeamTeamIdRouteImport } from './routes/_layout/dashboard/team/$teamId'
import { Route as LayoutDashboardSeasonSeasonIdRouteImport } from './routes/_layout/dashboard/season/$seasonId'
import { Route as LayoutDashboardGamesTodayRouteImport } from './routes/_layout/dashboard/games/$today'
import { Route as LayoutTeamsTeamIdTablesIndexRouteImport } from './routes/_layout/teams/$teamId/tables/index'
import { Route as LayoutTeamsTeamIdStatsIndexRouteImport } from './routes/_layout/teams/$teamId/stats/index'
import { Route as LayoutTeamsTeamIdSeasonsIndexRouteImport } from './routes/_layout/teams/$teamId/seasons/index'
import { Route as LayoutTeamsTeamIdLatestIndexRouteImport } from './routes/_layout/teams/$teamId/latest/index'
import { Route as LayoutSeasonsYearGroupIndexRouteImport } from './routes/_layout/seasons/$year/$group/index'
import { Route as LayoutDashboardSeasonSeasonIdIndexRouteImport } from './routes/_layout/dashboard/season/$seasonId/index'
import { Route as LayoutSeasonsYearPlayoffTableRouteImport } from './routes/_layout/seasons/$year/playoff/table'
import { Route as LayoutSeasonsYearPlayoffStatsRouteImport } from './routes/_layout/seasons/$year/playoff/stats'
import { Route as LayoutSeasonsYearPlayoffMapRouteImport } from './routes/_layout/seasons/$year/playoff/map'
import { Route as LayoutSeasonsYearPlayoffGamesRouteImport } from './routes/_layout/seasons/$year/playoff/games'
import { Route as LayoutSeasonsYearGroupTablesRouteImport } from './routes/_layout/seasons/$year/$group/tables'
import { Route as LayoutSeasonsYearGroupStatsRouteImport } from './routes/_layout/seasons/$year/$group/stats'
import { Route as LayoutSeasonsYearGroupMapRouteImport } from './routes/_layout/seasons/$year/$group/map'
import { Route as LayoutSeasonsYearGroupIntervalRouteImport } from './routes/_layout/seasons/$year/$group/interval'
import { Route as LayoutSeasonsYearGroupGamesRouteImport } from './routes/_layout/seasons/$year/$group/games'
import { Route as LayoutSeasonsYearGroupDevelopmentRouteImport } from './routes/_layout/seasons/$year/$group/development'
import { Route as LayoutTeamsTeamIdSeasonsSeasonIdIndexRouteImport } from './routes/_layout/teams/$teamId/seasons/$seasonId/index'
import { Route as LayoutDashboardSeasonSeasonIdTeamseasonIndexRouteImport } from './routes/_layout/dashboard/season/$seasonId/teamseason_/index'
import { Route as LayoutDashboardSeasonSeasonIdPlayoffseasonIndexRouteImport } from './routes/_layout/dashboard/season/$seasonId/playoffseason/index'
import { Route as LayoutDashboardSeasonSeasonIdMetadataIndexRouteImport } from './routes/_layout/dashboard/season/$seasonId/metadata/index'
import { Route as LayoutSeasonsYearGroupTablesTableRouteImport } from './routes/_layout/seasons/$year/$group/tables/$table'
import { Route as LayoutDashboardSeasonSeasonIdInfoSerieSerieIdRouteImport } from './routes/_layout/dashboard/season/$seasonId/info_/serie/$serieId'
import { Route as LayoutDashboardSeasonSeasonIdInfoCompetitionNewCompetitionRouteImport } from './routes/_layout/dashboard/season/$seasonId/info_/competition/newCompetition'
import { Route as LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdRouteImport } from './routes/_layout/dashboard/season/$seasonId/info_/competition/$competitionId'
import { Route as LayoutDashboardSeasonSeasonIdGamesSerieIdSerieIdRouteImport } from './routes/_layout/dashboard/season/$seasonId/games/$serieId/$serieId'
import { Route as LayoutDashboardSeasonSeasonIdGamesSerieIdEditIndexRouteImport } from './routes/_layout/dashboard/season/$seasonId/games_/$serieId/edit/index'
import { Route as LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRouteImport } from './routes/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit'
import { Route as LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdNewSerieRouteImport } from './routes/_layout/dashboard/season/$seasonId/info_/competition/$competitionId/newSerie'
import { Route as LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdEditRouteImport } from './routes/_layout/dashboard/season/$seasonId/info_/competition/$competitionId/edit'
import { Route as LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditSinglegameRouteImport } from './routes/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/singlegame'
import { Route as LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditNewParentIdRouteImport } from './routes/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/newParentId'
import { Route as LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGeneratescheduleRouteImport } from './routes/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/generateschedule'
import { Route as LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGamesRouteImport } from './routes/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/games'
import { Route as LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditEditTableRouteImport } from './routes/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/editTable'
import { Route as LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditEditParentIdRouteImport } from './routes/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/editParentId'
import { Route as LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditAddTableRouteImport } from './routes/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/addTable'
import { Route as LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditAddGamesRouteImport } from './routes/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/addGames'
import { Route as LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGameIdRouteImport } from './routes/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/$gameId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTeamsRoute = LayoutTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSeasonsRoute = LayoutSeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSearchRoute = LayoutSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUnauthorizedIndexRoute = LayoutUnauthorizedIndexRouteImport.update({
  id: '/unauthorized/',
  path: '/unauthorized/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSeasonsIndexRoute = LayoutSeasonsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutSeasonsRoute,
} as any)
const LayoutSearchIndexRoute = LayoutSearchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutSearchRoute,
} as any)
const LayoutLogoutIndexRoute = LayoutLogoutIndexRouteImport.update({
  id: '/logout/',
  path: '/logout/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLoginIndexRoute = LayoutLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardIndexRoute = LayoutDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutDashboardRoute,
} as any)
const LayoutAboutIndexRoute = LayoutAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutTeamsMapRoute = LayoutTeamsMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => LayoutTeamsRoute,
} as any)
const LayoutTeamsListRoute = LayoutTeamsListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => LayoutTeamsRoute,
} as any)
const LayoutTeamsCompareRoute = LayoutTeamsCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => LayoutTeamsRoute,
} as any)
const LayoutTeamsTeamIdRoute = LayoutTeamsTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => LayoutTeamsRoute,
} as any)
const LayoutSeasonsYearRoute = LayoutSeasonsYearRouteImport.update({
  id: '/$year',
  path: '/$year',
  getParentRoute: () => LayoutSeasonsRoute,
} as any)
const LayoutSearchHelpRoute = LayoutSearchHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => LayoutSearchRoute,
} as any)
const LayoutMaratonTableRoute = LayoutMaratonTableRouteImport.update({
  id: '/maraton/table',
  path: '/maraton/table',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMaratonRecordsRoute = LayoutMaratonRecordsRouteImport.update({
  id: '/maraton/records',
  path: '/maraton/records',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAboutChangelogRoute = LayoutAboutChangelogRouteImport.update({
  id: '/about/changelog',
  path: '/about/changelog',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMaratonHelpIndexRoute = LayoutMaratonHelpIndexRouteImport.update({
  id: '/maraton/help/',
  path: '/maraton/help/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardTeamsIndexRoute =
  LayoutDashboardTeamsIndexRouteImport.update({
    id: '/teams/',
    path: '/teams/',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)
const LayoutDashboardSeasonsIndexRoute =
  LayoutDashboardSeasonsIndexRouteImport.update({
    id: '/seasons/',
    path: '/seasons/',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)
const LayoutDashboardNewseasonIndexRoute =
  LayoutDashboardNewseasonIndexRouteImport.update({
    id: '/newseason/',
    path: '/newseason/',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)
const LayoutDashboardErrorIdIndexRoute =
  LayoutDashboardErrorIdIndexRouteImport.update({
    id: '/$errorId/',
    path: '/$errorId/',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)
const LayoutTeamsTeamIdSeasonIdRoute =
  LayoutTeamsTeamIdSeasonIdRouteImport.update({
    id: '/$seasonId',
    path: '/$seasonId',
    getParentRoute: () => LayoutTeamsTeamIdRoute,
  } as any)
const LayoutSeasonsYearPlayoffRoute =
  LayoutSeasonsYearPlayoffRouteImport.update({
    id: '/playoff',
    path: '/playoff',
    getParentRoute: () => LayoutSeasonsYearRoute,
  } as any)
const LayoutSeasonsYearGroupRoute = LayoutSeasonsYearGroupRouteImport.update({
  id: '/$group',
  path: '/$group',
  getParentRoute: () => LayoutSeasonsYearRoute,
} as any)
const LayoutMaratonTableMaratonTableRoute =
  LayoutMaratonTableMaratonTableRouteImport.update({
    id: '/$maratonTable',
    path: '/$maratonTable',
    getParentRoute: () => LayoutMaratonTableRoute,
  } as any)
const LayoutMaratonRecordsStreaksRoute =
  LayoutMaratonRecordsStreaksRouteImport.update({
    id: '/streaks',
    path: '/streaks',
    getParentRoute: () => LayoutMaratonRecordsRoute,
  } as any)
const LayoutMaratonRecordsStatsRoute =
  LayoutMaratonRecordsStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => LayoutMaratonRecordsRoute,
  } as any)
const LayoutMaratonRecordsScoredRoute =
  LayoutMaratonRecordsScoredRouteImport.update({
    id: '/scored',
    path: '/scored',
    getParentRoute: () => LayoutMaratonRecordsRoute,
  } as any)
const LayoutMaratonRecordsPointsRoute =
  LayoutMaratonRecordsPointsRouteImport.update({
    id: '/points',
    path: '/points',
    getParentRoute: () => LayoutMaratonRecordsRoute,
  } as any)
const LayoutMaratonRecordsConcededRoute =
  LayoutMaratonRecordsConcededRouteImport.update({
    id: '/conceded',
    path: '/conceded',
    getParentRoute: () => LayoutMaratonRecordsRoute,
  } as any)
const LayoutDashboardTeamsAddRoute = LayoutDashboardTeamsAddRouteImport.update({
  id: '/teams/add',
  path: '/teams/add',
  getParentRoute: () => LayoutDashboardRoute,
} as any)
const LayoutDashboardTeamTeamIdRoute =
  LayoutDashboardTeamTeamIdRouteImport.update({
    id: '/team/$teamId',
    path: '/team/$teamId',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)
const LayoutDashboardSeasonSeasonIdRoute =
  LayoutDashboardSeasonSeasonIdRouteImport.update({
    id: '/season/$seasonId',
    path: '/season/$seasonId',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)
const LayoutDashboardGamesTodayRoute =
  LayoutDashboardGamesTodayRouteImport.update({
    id: '/games/$today',
    path: '/games/$today',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)
const LayoutTeamsTeamIdTablesIndexRoute =
  LayoutTeamsTeamIdTablesIndexRouteImport.update({
    id: '/tables/',
    path: '/tables/',
    getParentRoute: () => LayoutTeamsTeamIdRoute,
  } as any)
const LayoutTeamsTeamIdStatsIndexRoute =
  LayoutTeamsTeamIdStatsIndexRouteImport.update({
    id: '/stats/',
    path: '/stats/',
    getParentRoute: () => LayoutTeamsTeamIdRoute,
  } as any)
const LayoutTeamsTeamIdSeasonsIndexRoute =
  LayoutTeamsTeamIdSeasonsIndexRouteImport.update({
    id: '/seasons/',
    path: '/seasons/',
    getParentRoute: () => LayoutTeamsTeamIdRoute,
  } as any)
const LayoutTeamsTeamIdLatestIndexRoute =
  LayoutTeamsTeamIdLatestIndexRouteImport.update({
    id: '/latest/',
    path: '/latest/',
    getParentRoute: () => LayoutTeamsTeamIdRoute,
  } as any)
const LayoutSeasonsYearGroupIndexRoute =
  LayoutSeasonsYearGroupIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutSeasonsYearGroupRoute,
  } as any)
const LayoutDashboardSeasonSeasonIdIndexRoute =
  LayoutDashboardSeasonSeasonIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutDashboardSeasonSeasonIdRoute,
  } as any)
const LayoutSeasonsYearPlayoffTableRoute =
  LayoutSeasonsYearPlayoffTableRouteImport.update({
    id: '/table',
    path: '/table',
    getParentRoute: () => LayoutSeasonsYearPlayoffRoute,
  } as any)
const LayoutSeasonsYearPlayoffStatsRoute =
  LayoutSeasonsYearPlayoffStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => LayoutSeasonsYearPlayoffRoute,
  } as any)
const LayoutSeasonsYearPlayoffMapRoute =
  LayoutSeasonsYearPlayoffMapRouteImport.update({
    id: '/map',
    path: '/map',
    getParentRoute: () => LayoutSeasonsYearPlayoffRoute,
  } as any)
const LayoutSeasonsYearPlayoffGamesRoute =
  LayoutSeasonsYearPlayoffGamesRouteImport.update({
    id: '/games',
    path: '/games',
    getParentRoute: () => LayoutSeasonsYearPlayoffRoute,
  } as any)
const LayoutSeasonsYearGroupTablesRoute =
  LayoutSeasonsYearGroupTablesRouteImport.update({
    id: '/tables',
    path: '/tables',
    getParentRoute: () => LayoutSeasonsYearGroupRoute,
  } as any)
const LayoutSeasonsYearGroupStatsRoute =
  LayoutSeasonsYearGroupStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => LayoutSeasonsYearGroupRoute,
  } as any)
const LayoutSeasonsYearGroupMapRoute =
  LayoutSeasonsYearGroupMapRouteImport.update({
    id: '/map',
    path: '/map',
    getParentRoute: () => LayoutSeasonsYearGroupRoute,
  } as any)
const LayoutSeasonsYearGroupIntervalRoute =
  LayoutSeasonsYearGroupIntervalRouteImport.update({
    id: '/interval',
    path: '/interval',
    getParentRoute: () => LayoutSeasonsYearGroupRoute,
  } as any)
const LayoutSeasonsYearGroupGamesRoute =
  LayoutSeasonsYearGroupGamesRouteImport.update({
    id: '/games',
    path: '/games',
    getParentRoute: () => LayoutSeasonsYearGroupRoute,
  } as any)
const LayoutSeasonsYearGroupDevelopmentRoute =
  LayoutSeasonsYearGroupDevelopmentRouteImport.update({
    id: '/development',
    path: '/development',
    getParentRoute: () => LayoutSeasonsYearGroupRoute,
  } as any)
const LayoutTeamsTeamIdSeasonsSeasonIdIndexRoute =
  LayoutTeamsTeamIdSeasonsSeasonIdIndexRouteImport.update({
    id: '/seasons/$seasonId/',
    path: '/seasons/$seasonId/',
    getParentRoute: () => LayoutTeamsTeamIdRoute,
  } as any)
const LayoutDashboardSeasonSeasonIdTeamseasonIndexRoute =
  LayoutDashboardSeasonSeasonIdTeamseasonIndexRouteImport.update({
    id: '/teamseason_/',
    path: '/teamseason/',
    getParentRoute: () => LayoutDashboardSeasonSeasonIdRoute,
  } as any)
const LayoutDashboardSeasonSeasonIdPlayoffseasonIndexRoute =
  LayoutDashboardSeasonSeasonIdPlayoffseasonIndexRouteImport.update({
    id: '/playoffseason/',
    path: '/playoffseason/',
    getParentRoute: () => LayoutDashboardSeasonSeasonIdRoute,
  } as any)
const LayoutDashboardSeasonSeasonIdMetadataIndexRoute =
  LayoutDashboardSeasonSeasonIdMetadataIndexRouteImport.update({
    id: '/metadata/',
    path: '/metadata/',
    getParentRoute: () => LayoutDashboardSeasonSeasonIdRoute,
  } as any)
const LayoutSeasonsYearGroupTablesTableRoute =
  LayoutSeasonsYearGroupTablesTableRouteImport.update({
    id: '/$table',
    path: '/$table',
    getParentRoute: () => LayoutSeasonsYearGroupTablesRoute,
  } as any)
const LayoutDashboardSeasonSeasonIdInfoSerieSerieIdRoute =
  LayoutDashboardSeasonSeasonIdInfoSerieSerieIdRouteImport.update({
    id: '/info_/serie/$serieId',
    path: '/info/serie/$serieId',
    getParentRoute: () => LayoutDashboardSeasonSeasonIdRoute,
  } as any)
const LayoutDashboardSeasonSeasonIdInfoCompetitionNewCompetitionRoute =
  LayoutDashboardSeasonSeasonIdInfoCompetitionNewCompetitionRouteImport.update({
    id: '/info_/competition/newCompetition',
    path: '/info/competition/newCompetition',
    getParentRoute: () => LayoutDashboardSeasonSeasonIdRoute,
  } as any)
const LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdRoute =
  LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdRouteImport.update({
    id: '/info_/competition/$competitionId',
    path: '/info/competition/$competitionId',
    getParentRoute: () => LayoutDashboardSeasonSeasonIdRoute,
  } as any)
const LayoutDashboardSeasonSeasonIdGamesSerieIdSerieIdRoute =
  LayoutDashboardSeasonSeasonIdGamesSerieIdSerieIdRouteImport.update({
    id: '/games/$serieId/$serieId',
    path: '/games/$serieId/$serieId',
    getParentRoute: () => LayoutDashboardSeasonSeasonIdRoute,
  } as any)
const LayoutDashboardSeasonSeasonIdGamesSerieIdEditIndexRoute =
  LayoutDashboardSeasonSeasonIdGamesSerieIdEditIndexRouteImport.update({
    id: '/games_/$serieId/edit/',
    path: '/games/$serieId/edit/',
    getParentRoute: () => LayoutDashboardSeasonSeasonIdRoute,
  } as any)
const LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRoute =
  LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => LayoutDashboardSeasonSeasonIdInfoSerieSerieIdRoute,
  } as any)
const LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdNewSerieRoute =
  LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdNewSerieRouteImport.update(
    {
      id: '/newSerie',
      path: '/newSerie',
      getParentRoute: () =>
        LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdRoute,
    } as any,
  )
const LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdEditRoute =
  LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdEditRouteImport.update(
    {
      id: '/edit',
      path: '/edit',
      getParentRoute: () =>
        LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdRoute,
    } as any,
  )
const LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditSinglegameRoute =
  LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditSinglegameRouteImport.update(
    {
      id: '/singlegame',
      path: '/singlegame',
      getParentRoute: () =>
        LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRoute,
    } as any,
  )
const LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditNewParentIdRoute =
  LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditNewParentIdRouteImport.update(
    {
      id: '/newParentId',
      path: '/newParentId',
      getParentRoute: () =>
        LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRoute,
    } as any,
  )
const LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGeneratescheduleRoute =
  LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGeneratescheduleRouteImport.update(
    {
      id: '/generateschedule',
      path: '/generateschedule',
      getParentRoute: () =>
        LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRoute,
    } as any,
  )
const LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGamesRoute =
  LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGamesRouteImport.update({
    id: '/games',
    path: '/games',
    getParentRoute: () =>
      LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRoute,
  } as any)
const LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditEditTableRoute =
  LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditEditTableRouteImport.update({
    id: '/editTable',
    path: '/editTable',
    getParentRoute: () =>
      LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRoute,
  } as any)
const LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditEditParentIdRoute =
  LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditEditParentIdRouteImport.update(
    {
      id: '/editParentId',
      path: '/editParentId',
      getParentRoute: () =>
        LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRoute,
    } as any,
  )
const LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditAddTableRoute =
  LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditAddTableRouteImport.update({
    id: '/addTable',
    path: '/addTable',
    getParentRoute: () =>
      LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRoute,
  } as any)
const LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditAddGamesRoute =
  LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditAddGamesRouteImport.update({
    id: '/addGames',
    path: '/addGames',
    getParentRoute: () =>
      LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRoute,
  } as any)
const LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGameIdRoute =
  LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGameIdRouteImport.update({
    id: '/$gameId',
    path: '/$gameId',
    getParentRoute: () =>
      LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/dashboard': typeof LayoutDashboardRouteWithChildren
  '/search': typeof LayoutSearchRouteWithChildren
  '/seasons': typeof LayoutSeasonsRouteWithChildren
  '/teams': typeof LayoutTeamsRouteWithChildren
  '/about/changelog': typeof LayoutAboutChangelogRoute
  '/maraton/records': typeof LayoutMaratonRecordsRouteWithChildren
  '/maraton/table': typeof LayoutMaratonTableRouteWithChildren
  '/search/help': typeof LayoutSearchHelpRoute
  '/seasons/$year': typeof LayoutSeasonsYearRouteWithChildren
  '/teams/$teamId': typeof LayoutTeamsTeamIdRouteWithChildren
  '/teams/compare': typeof LayoutTeamsCompareRoute
  '/teams/list': typeof LayoutTeamsListRoute
  '/teams/map': typeof LayoutTeamsMapRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/about/': typeof LayoutAboutIndexRoute
  '/dashboard/': typeof LayoutDashboardIndexRoute
  '/login/': typeof LayoutLoginIndexRoute
  '/logout/': typeof LayoutLogoutIndexRoute
  '/search/': typeof LayoutSearchIndexRoute
  '/seasons/': typeof LayoutSeasonsIndexRoute
  '/unauthorized/': typeof LayoutUnauthorizedIndexRoute
  '/dashboard/games/$today': typeof LayoutDashboardGamesTodayRoute
  '/dashboard/season/$seasonId': typeof LayoutDashboardSeasonSeasonIdRouteWithChildren
  '/dashboard/team/$teamId': typeof LayoutDashboardTeamTeamIdRoute
  '/dashboard/teams/add': typeof LayoutDashboardTeamsAddRoute
  '/maraton/records/conceded': typeof LayoutMaratonRecordsConcededRoute
  '/maraton/records/points': typeof LayoutMaratonRecordsPointsRoute
  '/maraton/records/scored': typeof LayoutMaratonRecordsScoredRoute
  '/maraton/records/stats': typeof LayoutMaratonRecordsStatsRoute
  '/maraton/records/streaks': typeof LayoutMaratonRecordsStreaksRoute
  '/maraton/table/$maratonTable': typeof LayoutMaratonTableMaratonTableRoute
  '/seasons/$year/$group': typeof LayoutSeasonsYearGroupRouteWithChildren
  '/seasons/$year/playoff': typeof LayoutSeasonsYearPlayoffRouteWithChildren
  '/teams/$teamId/$seasonId': typeof LayoutTeamsTeamIdSeasonIdRoute
  '/dashboard/$errorId/': typeof LayoutDashboardErrorIdIndexRoute
  '/dashboard/newseason/': typeof LayoutDashboardNewseasonIndexRoute
  '/dashboard/seasons/': typeof LayoutDashboardSeasonsIndexRoute
  '/dashboard/teams/': typeof LayoutDashboardTeamsIndexRoute
  '/maraton/help/': typeof LayoutMaratonHelpIndexRoute
  '/seasons/$year/$group/development': typeof LayoutSeasonsYearGroupDevelopmentRoute
  '/seasons/$year/$group/games': typeof LayoutSeasonsYearGroupGamesRoute
  '/seasons/$year/$group/interval': typeof LayoutSeasonsYearGroupIntervalRoute
  '/seasons/$year/$group/map': typeof LayoutSeasonsYearGroupMapRoute
  '/seasons/$year/$group/stats': typeof LayoutSeasonsYearGroupStatsRoute
  '/seasons/$year/$group/tables': typeof LayoutSeasonsYearGroupTablesRouteWithChildren
  '/seasons/$year/playoff/games': typeof LayoutSeasonsYearPlayoffGamesRoute
  '/seasons/$year/playoff/map': typeof LayoutSeasonsYearPlayoffMapRoute
  '/seasons/$year/playoff/stats': typeof LayoutSeasonsYearPlayoffStatsRoute
  '/seasons/$year/playoff/table': typeof LayoutSeasonsYearPlayoffTableRoute
  '/dashboard/season/$seasonId/': typeof LayoutDashboardSeasonSeasonIdIndexRoute
  '/seasons/$year/$group/': typeof LayoutSeasonsYearGroupIndexRoute
  '/teams/$teamId/latest/': typeof LayoutTeamsTeamIdLatestIndexRoute
  '/teams/$teamId/seasons/': typeof LayoutTeamsTeamIdSeasonsIndexRoute
  '/teams/$teamId/stats/': typeof LayoutTeamsTeamIdStatsIndexRoute
  '/teams/$teamId/tables/': typeof LayoutTeamsTeamIdTablesIndexRoute
  '/seasons/$year/$group/tables/$table': typeof LayoutSeasonsYearGroupTablesTableRoute
  '/dashboard/season/$seasonId/metadata/': typeof LayoutDashboardSeasonSeasonIdMetadataIndexRoute
  '/dashboard/season/$seasonId/playoffseason/': typeof LayoutDashboardSeasonSeasonIdPlayoffseasonIndexRoute
  '/dashboard/season/$seasonId/teamseason/': typeof LayoutDashboardSeasonSeasonIdTeamseasonIndexRoute
  '/teams/$teamId/seasons/$seasonId/': typeof LayoutTeamsTeamIdSeasonsSeasonIdIndexRoute
  '/dashboard/season/$seasonId/games/$serieId/$serieId': typeof LayoutDashboardSeasonSeasonIdGamesSerieIdSerieIdRoute
  '/dashboard/season/$seasonId/info/competition/$competitionId': typeof LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdRouteWithChildren
  '/dashboard/season/$seasonId/info/competition/newCompetition': typeof LayoutDashboardSeasonSeasonIdInfoCompetitionNewCompetitionRoute
  '/dashboard/season/$seasonId/info/serie/$serieId': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdRouteWithChildren
  '/dashboard/season/$seasonId/info/competition/$competitionId/edit': typeof LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdEditRoute
  '/dashboard/season/$seasonId/info/competition/$competitionId/newSerie': typeof LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdNewSerieRoute
  '/dashboard/season/$seasonId/info/serie/$serieId/edit': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRouteWithChildren
  '/dashboard/season/$seasonId/games/$serieId/edit/': typeof LayoutDashboardSeasonSeasonIdGamesSerieIdEditIndexRoute
  '/dashboard/season/$seasonId/info/serie/$serieId/edit/$gameId': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGameIdRoute
  '/dashboard/season/$seasonId/info/serie/$serieId/edit/addGames': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditAddGamesRoute
  '/dashboard/season/$seasonId/info/serie/$serieId/edit/addTable': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditAddTableRoute
  '/dashboard/season/$seasonId/info/serie/$serieId/edit/editParentId': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditEditParentIdRoute
  '/dashboard/season/$seasonId/info/serie/$serieId/edit/editTable': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditEditTableRoute
  '/dashboard/season/$seasonId/info/serie/$serieId/edit/games': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGamesRoute
  '/dashboard/season/$seasonId/info/serie/$serieId/edit/generateschedule': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGeneratescheduleRoute
  '/dashboard/season/$seasonId/info/serie/$serieId/edit/newParentId': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditNewParentIdRoute
  '/dashboard/season/$seasonId/info/serie/$serieId/edit/singlegame': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditSinglegameRoute
}
export interface FileRoutesByTo {
  '/teams': typeof LayoutTeamsRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/about/changelog': typeof LayoutAboutChangelogRoute
  '/maraton/records': typeof LayoutMaratonRecordsRouteWithChildren
  '/maraton/table': typeof LayoutMaratonTableRouteWithChildren
  '/search/help': typeof LayoutSearchHelpRoute
  '/seasons/$year': typeof LayoutSeasonsYearRouteWithChildren
  '/teams/$teamId': typeof LayoutTeamsTeamIdRouteWithChildren
  '/teams/compare': typeof LayoutTeamsCompareRoute
  '/teams/list': typeof LayoutTeamsListRoute
  '/teams/map': typeof LayoutTeamsMapRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/about': typeof LayoutAboutIndexRoute
  '/dashboard': typeof LayoutDashboardIndexRoute
  '/login': typeof LayoutLoginIndexRoute
  '/logout': typeof LayoutLogoutIndexRoute
  '/search': typeof LayoutSearchIndexRoute
  '/seasons': typeof LayoutSeasonsIndexRoute
  '/unauthorized': typeof LayoutUnauthorizedIndexRoute
  '/dashboard/games/$today': typeof LayoutDashboardGamesTodayRoute
  '/dashboard/team/$teamId': typeof LayoutDashboardTeamTeamIdRoute
  '/dashboard/teams/add': typeof LayoutDashboardTeamsAddRoute
  '/maraton/records/conceded': typeof LayoutMaratonRecordsConcededRoute
  '/maraton/records/points': typeof LayoutMaratonRecordsPointsRoute
  '/maraton/records/scored': typeof LayoutMaratonRecordsScoredRoute
  '/maraton/records/stats': typeof LayoutMaratonRecordsStatsRoute
  '/maraton/records/streaks': typeof LayoutMaratonRecordsStreaksRoute
  '/maraton/table/$maratonTable': typeof LayoutMaratonTableMaratonTableRoute
  '/seasons/$year/playoff': typeof LayoutSeasonsYearPlayoffRouteWithChildren
  '/teams/$teamId/$seasonId': typeof LayoutTeamsTeamIdSeasonIdRoute
  '/dashboard/$errorId': typeof LayoutDashboardErrorIdIndexRoute
  '/dashboard/newseason': typeof LayoutDashboardNewseasonIndexRoute
  '/dashboard/seasons': typeof LayoutDashboardSeasonsIndexRoute
  '/dashboard/teams': typeof LayoutDashboardTeamsIndexRoute
  '/maraton/help': typeof LayoutMaratonHelpIndexRoute
  '/seasons/$year/$group/development': typeof LayoutSeasonsYearGroupDevelopmentRoute
  '/seasons/$year/$group/games': typeof LayoutSeasonsYearGroupGamesRoute
  '/seasons/$year/$group/interval': typeof LayoutSeasonsYearGroupIntervalRoute
  '/seasons/$year/$group/map': typeof LayoutSeasonsYearGroupMapRoute
  '/seasons/$year/$group/stats': typeof LayoutSeasonsYearGroupStatsRoute
  '/seasons/$year/$group/tables': typeof LayoutSeasonsYearGroupTablesRouteWithChildren
  '/seasons/$year/playoff/games': typeof LayoutSeasonsYearPlayoffGamesRoute
  '/seasons/$year/playoff/map': typeof LayoutSeasonsYearPlayoffMapRoute
  '/seasons/$year/playoff/stats': typeof LayoutSeasonsYearPlayoffStatsRoute
  '/seasons/$year/playoff/table': typeof LayoutSeasonsYearPlayoffTableRoute
  '/dashboard/season/$seasonId': typeof LayoutDashboardSeasonSeasonIdIndexRoute
  '/seasons/$year/$group': typeof LayoutSeasonsYearGroupIndexRoute
  '/teams/$teamId/latest': typeof LayoutTeamsTeamIdLatestIndexRoute
  '/teams/$teamId/seasons': typeof LayoutTeamsTeamIdSeasonsIndexRoute
  '/teams/$teamId/stats': typeof LayoutTeamsTeamIdStatsIndexRoute
  '/teams/$teamId/tables': typeof LayoutTeamsTeamIdTablesIndexRoute
  '/seasons/$year/$group/tables/$table': typeof LayoutSeasonsYearGroupTablesTableRoute
  '/dashboard/season/$seasonId/metadata': typeof LayoutDashboardSeasonSeasonIdMetadataIndexRoute
  '/dashboard/season/$seasonId/playoffseason': typeof LayoutDashboardSeasonSeasonIdPlayoffseasonIndexRoute
  '/dashboard/season/$seasonId/teamseason': typeof LayoutDashboardSeasonSeasonIdTeamseasonIndexRoute
  '/teams/$teamId/seasons/$seasonId': typeof LayoutTeamsTeamIdSeasonsSeasonIdIndexRoute
  '/dashboard/season/$seasonId/games/$serieId/$serieId': typeof LayoutDashboardSeasonSeasonIdGamesSerieIdSerieIdRoute
  '/dashboard/season/$seasonId/info/competition/$competitionId': typeof LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdRouteWithChildren
  '/dashboard/season/$seasonId/info/competition/newCompetition': typeof LayoutDashboardSeasonSeasonIdInfoCompetitionNewCompetitionRoute
  '/dashboard/season/$seasonId/info/serie/$serieId': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdRouteWithChildren
  '/dashboard/season/$seasonId/info/competition/$competitionId/edit': typeof LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdEditRoute
  '/dashboard/season/$seasonId/info/competition/$competitionId/newSerie': typeof LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdNewSerieRoute
  '/dashboard/season/$seasonId/info/serie/$serieId/edit': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRouteWithChildren
  '/dashboard/season/$seasonId/games/$serieId/edit': typeof LayoutDashboardSeasonSeasonIdGamesSerieIdEditIndexRoute
  '/dashboard/season/$seasonId/info/serie/$serieId/edit/$gameId': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGameIdRoute
  '/dashboard/season/$seasonId/info/serie/$serieId/edit/addGames': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditAddGamesRoute
  '/dashboard/season/$seasonId/info/serie/$serieId/edit/addTable': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditAddTableRoute
  '/dashboard/season/$seasonId/info/serie/$serieId/edit/editParentId': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditEditParentIdRoute
  '/dashboard/season/$seasonId/info/serie/$serieId/edit/editTable': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditEditTableRoute
  '/dashboard/season/$seasonId/info/serie/$serieId/edit/games': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGamesRoute
  '/dashboard/season/$seasonId/info/serie/$serieId/edit/generateschedule': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGeneratescheduleRoute
  '/dashboard/season/$seasonId/info/serie/$serieId/edit/newParentId': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditNewParentIdRoute
  '/dashboard/season/$seasonId/info/serie/$serieId/edit/singlegame': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditSinglegameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/dashboard': typeof LayoutDashboardRouteWithChildren
  '/_layout/search': typeof LayoutSearchRouteWithChildren
  '/_layout/seasons': typeof LayoutSeasonsRouteWithChildren
  '/_layout/teams': typeof LayoutTeamsRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/about/changelog': typeof LayoutAboutChangelogRoute
  '/_layout/maraton/records': typeof LayoutMaratonRecordsRouteWithChildren
  '/_layout/maraton/table': typeof LayoutMaratonTableRouteWithChildren
  '/_layout/search/help': typeof LayoutSearchHelpRoute
  '/_layout/seasons/$year': typeof LayoutSeasonsYearRouteWithChildren
  '/_layout/teams/$teamId': typeof LayoutTeamsTeamIdRouteWithChildren
  '/_layout/teams/compare': typeof LayoutTeamsCompareRoute
  '/_layout/teams/list': typeof LayoutTeamsListRoute
  '/_layout/teams/map': typeof LayoutTeamsMapRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/_layout/about/': typeof LayoutAboutIndexRoute
  '/_layout/dashboard/': typeof LayoutDashboardIndexRoute
  '/_layout/login/': typeof LayoutLoginIndexRoute
  '/_layout/logout/': typeof LayoutLogoutIndexRoute
  '/_layout/search/': typeof LayoutSearchIndexRoute
  '/_layout/seasons/': typeof LayoutSeasonsIndexRoute
  '/_layout/unauthorized/': typeof LayoutUnauthorizedIndexRoute
  '/_layout/dashboard/games/$today': typeof LayoutDashboardGamesTodayRoute
  '/_layout/dashboard/season/$seasonId': typeof LayoutDashboardSeasonSeasonIdRouteWithChildren
  '/_layout/dashboard/team/$teamId': typeof LayoutDashboardTeamTeamIdRoute
  '/_layout/dashboard/teams/add': typeof LayoutDashboardTeamsAddRoute
  '/_layout/maraton/records/conceded': typeof LayoutMaratonRecordsConcededRoute
  '/_layout/maraton/records/points': typeof LayoutMaratonRecordsPointsRoute
  '/_layout/maraton/records/scored': typeof LayoutMaratonRecordsScoredRoute
  '/_layout/maraton/records/stats': typeof LayoutMaratonRecordsStatsRoute
  '/_layout/maraton/records/streaks': typeof LayoutMaratonRecordsStreaksRoute
  '/_layout/maraton/table/$maratonTable': typeof LayoutMaratonTableMaratonTableRoute
  '/_layout/seasons/$year/$group': typeof LayoutSeasonsYearGroupRouteWithChildren
  '/_layout/seasons/$year/playoff': typeof LayoutSeasonsYearPlayoffRouteWithChildren
  '/_layout/teams/$teamId/$seasonId': typeof LayoutTeamsTeamIdSeasonIdRoute
  '/_layout/dashboard/$errorId/': typeof LayoutDashboardErrorIdIndexRoute
  '/_layout/dashboard/newseason/': typeof LayoutDashboardNewseasonIndexRoute
  '/_layout/dashboard/seasons/': typeof LayoutDashboardSeasonsIndexRoute
  '/_layout/dashboard/teams/': typeof LayoutDashboardTeamsIndexRoute
  '/_layout/maraton/help/': typeof LayoutMaratonHelpIndexRoute
  '/_layout/seasons/$year/$group/development': typeof LayoutSeasonsYearGroupDevelopmentRoute
  '/_layout/seasons/$year/$group/games': typeof LayoutSeasonsYearGroupGamesRoute
  '/_layout/seasons/$year/$group/interval': typeof LayoutSeasonsYearGroupIntervalRoute
  '/_layout/seasons/$year/$group/map': typeof LayoutSeasonsYearGroupMapRoute
  '/_layout/seasons/$year/$group/stats': typeof LayoutSeasonsYearGroupStatsRoute
  '/_layout/seasons/$year/$group/tables': typeof LayoutSeasonsYearGroupTablesRouteWithChildren
  '/_layout/seasons/$year/playoff/games': typeof LayoutSeasonsYearPlayoffGamesRoute
  '/_layout/seasons/$year/playoff/map': typeof LayoutSeasonsYearPlayoffMapRoute
  '/_layout/seasons/$year/playoff/stats': typeof LayoutSeasonsYearPlayoffStatsRoute
  '/_layout/seasons/$year/playoff/table': typeof LayoutSeasonsYearPlayoffTableRoute
  '/_layout/dashboard/season/$seasonId/': typeof LayoutDashboardSeasonSeasonIdIndexRoute
  '/_layout/seasons/$year/$group/': typeof LayoutSeasonsYearGroupIndexRoute
  '/_layout/teams/$teamId/latest/': typeof LayoutTeamsTeamIdLatestIndexRoute
  '/_layout/teams/$teamId/seasons/': typeof LayoutTeamsTeamIdSeasonsIndexRoute
  '/_layout/teams/$teamId/stats/': typeof LayoutTeamsTeamIdStatsIndexRoute
  '/_layout/teams/$teamId/tables/': typeof LayoutTeamsTeamIdTablesIndexRoute
  '/_layout/seasons/$year/$group/tables/$table': typeof LayoutSeasonsYearGroupTablesTableRoute
  '/_layout/dashboard/season/$seasonId/metadata/': typeof LayoutDashboardSeasonSeasonIdMetadataIndexRoute
  '/_layout/dashboard/season/$seasonId/playoffseason/': typeof LayoutDashboardSeasonSeasonIdPlayoffseasonIndexRoute
  '/_layout/dashboard/season/$seasonId/teamseason_/': typeof LayoutDashboardSeasonSeasonIdTeamseasonIndexRoute
  '/_layout/teams/$teamId/seasons/$seasonId/': typeof LayoutTeamsTeamIdSeasonsSeasonIdIndexRoute
  '/_layout/dashboard/season/$seasonId/games/$serieId/$serieId': typeof LayoutDashboardSeasonSeasonIdGamesSerieIdSerieIdRoute
  '/_layout/dashboard/season/$seasonId/info_/competition/$competitionId': typeof LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdRouteWithChildren
  '/_layout/dashboard/season/$seasonId/info_/competition/newCompetition': typeof LayoutDashboardSeasonSeasonIdInfoCompetitionNewCompetitionRoute
  '/_layout/dashboard/season/$seasonId/info_/serie/$serieId': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdRouteWithChildren
  '/_layout/dashboard/season/$seasonId/info_/competition/$competitionId/edit': typeof LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdEditRoute
  '/_layout/dashboard/season/$seasonId/info_/competition/$competitionId/newSerie': typeof LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdNewSerieRoute
  '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRouteWithChildren
  '/_layout/dashboard/season/$seasonId/games_/$serieId/edit/': typeof LayoutDashboardSeasonSeasonIdGamesSerieIdEditIndexRoute
  '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/$gameId': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGameIdRoute
  '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/addGames': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditAddGamesRoute
  '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/addTable': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditAddTableRoute
  '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/editParentId': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditEditParentIdRoute
  '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/editTable': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditEditTableRoute
  '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/games': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGamesRoute
  '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/generateschedule': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGeneratescheduleRoute
  '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/newParentId': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditNewParentIdRoute
  '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/singlegame': typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditSinglegameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/search'
    | '/seasons'
    | '/teams'
    | '/about/changelog'
    | '/maraton/records'
    | '/maraton/table'
    | '/search/help'
    | '/seasons/$year'
    | '/teams/$teamId'
    | '/teams/compare'
    | '/teams/list'
    | '/teams/map'
    | '/api/v1/health'
    | '/about/'
    | '/dashboard/'
    | '/login/'
    | '/logout/'
    | '/search/'
    | '/seasons/'
    | '/unauthorized/'
    | '/dashboard/games/$today'
    | '/dashboard/season/$seasonId'
    | '/dashboard/team/$teamId'
    | '/dashboard/teams/add'
    | '/maraton/records/conceded'
    | '/maraton/records/points'
    | '/maraton/records/scored'
    | '/maraton/records/stats'
    | '/maraton/records/streaks'
    | '/maraton/table/$maratonTable'
    | '/seasons/$year/$group'
    | '/seasons/$year/playoff'
    | '/teams/$teamId/$seasonId'
    | '/dashboard/$errorId/'
    | '/dashboard/newseason/'
    | '/dashboard/seasons/'
    | '/dashboard/teams/'
    | '/maraton/help/'
    | '/seasons/$year/$group/development'
    | '/seasons/$year/$group/games'
    | '/seasons/$year/$group/interval'
    | '/seasons/$year/$group/map'
    | '/seasons/$year/$group/stats'
    | '/seasons/$year/$group/tables'
    | '/seasons/$year/playoff/games'
    | '/seasons/$year/playoff/map'
    | '/seasons/$year/playoff/stats'
    | '/seasons/$year/playoff/table'
    | '/dashboard/season/$seasonId/'
    | '/seasons/$year/$group/'
    | '/teams/$teamId/latest/'
    | '/teams/$teamId/seasons/'
    | '/teams/$teamId/stats/'
    | '/teams/$teamId/tables/'
    | '/seasons/$year/$group/tables/$table'
    | '/dashboard/season/$seasonId/metadata/'
    | '/dashboard/season/$seasonId/playoffseason/'
    | '/dashboard/season/$seasonId/teamseason/'
    | '/teams/$teamId/seasons/$seasonId/'
    | '/dashboard/season/$seasonId/games/$serieId/$serieId'
    | '/dashboard/season/$seasonId/info/competition/$competitionId'
    | '/dashboard/season/$seasonId/info/competition/newCompetition'
    | '/dashboard/season/$seasonId/info/serie/$serieId'
    | '/dashboard/season/$seasonId/info/competition/$competitionId/edit'
    | '/dashboard/season/$seasonId/info/competition/$competitionId/newSerie'
    | '/dashboard/season/$seasonId/info/serie/$serieId/edit'
    | '/dashboard/season/$seasonId/games/$serieId/edit/'
    | '/dashboard/season/$seasonId/info/serie/$serieId/edit/$gameId'
    | '/dashboard/season/$seasonId/info/serie/$serieId/edit/addGames'
    | '/dashboard/season/$seasonId/info/serie/$serieId/edit/addTable'
    | '/dashboard/season/$seasonId/info/serie/$serieId/edit/editParentId'
    | '/dashboard/season/$seasonId/info/serie/$serieId/edit/editTable'
    | '/dashboard/season/$seasonId/info/serie/$serieId/edit/games'
    | '/dashboard/season/$seasonId/info/serie/$serieId/edit/generateschedule'
    | '/dashboard/season/$seasonId/info/serie/$serieId/edit/newParentId'
    | '/dashboard/season/$seasonId/info/serie/$serieId/edit/singlegame'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/teams'
    | '/'
    | '/about/changelog'
    | '/maraton/records'
    | '/maraton/table'
    | '/search/help'
    | '/seasons/$year'
    | '/teams/$teamId'
    | '/teams/compare'
    | '/teams/list'
    | '/teams/map'
    | '/api/v1/health'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/logout'
    | '/search'
    | '/seasons'
    | '/unauthorized'
    | '/dashboard/games/$today'
    | '/dashboard/team/$teamId'
    | '/dashboard/teams/add'
    | '/maraton/records/conceded'
    | '/maraton/records/points'
    | '/maraton/records/scored'
    | '/maraton/records/stats'
    | '/maraton/records/streaks'
    | '/maraton/table/$maratonTable'
    | '/seasons/$year/playoff'
    | '/teams/$teamId/$seasonId'
    | '/dashboard/$errorId'
    | '/dashboard/newseason'
    | '/dashboard/seasons'
    | '/dashboard/teams'
    | '/maraton/help'
    | '/seasons/$year/$group/development'
    | '/seasons/$year/$group/games'
    | '/seasons/$year/$group/interval'
    | '/seasons/$year/$group/map'
    | '/seasons/$year/$group/stats'
    | '/seasons/$year/$group/tables'
    | '/seasons/$year/playoff/games'
    | '/seasons/$year/playoff/map'
    | '/seasons/$year/playoff/stats'
    | '/seasons/$year/playoff/table'
    | '/dashboard/season/$seasonId'
    | '/seasons/$year/$group'
    | '/teams/$teamId/latest'
    | '/teams/$teamId/seasons'
    | '/teams/$teamId/stats'
    | '/teams/$teamId/tables'
    | '/seasons/$year/$group/tables/$table'
    | '/dashboard/season/$seasonId/metadata'
    | '/dashboard/season/$seasonId/playoffseason'
    | '/dashboard/season/$seasonId/teamseason'
    | '/teams/$teamId/seasons/$seasonId'
    | '/dashboard/season/$seasonId/games/$serieId/$serieId'
    | '/dashboard/season/$seasonId/info/competition/$competitionId'
    | '/dashboard/season/$seasonId/info/competition/newCompetition'
    | '/dashboard/season/$seasonId/info/serie/$serieId'
    | '/dashboard/season/$seasonId/info/competition/$competitionId/edit'
    | '/dashboard/season/$seasonId/info/competition/$competitionId/newSerie'
    | '/dashboard/season/$seasonId/info/serie/$serieId/edit'
    | '/dashboard/season/$seasonId/games/$serieId/edit'
    | '/dashboard/season/$seasonId/info/serie/$serieId/edit/$gameId'
    | '/dashboard/season/$seasonId/info/serie/$serieId/edit/addGames'
    | '/dashboard/season/$seasonId/info/serie/$serieId/edit/addTable'
    | '/dashboard/season/$seasonId/info/serie/$serieId/edit/editParentId'
    | '/dashboard/season/$seasonId/info/serie/$serieId/edit/editTable'
    | '/dashboard/season/$seasonId/info/serie/$serieId/edit/games'
    | '/dashboard/season/$seasonId/info/serie/$serieId/edit/generateschedule'
    | '/dashboard/season/$seasonId/info/serie/$serieId/edit/newParentId'
    | '/dashboard/season/$seasonId/info/serie/$serieId/edit/singlegame'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/dashboard'
    | '/_layout/search'
    | '/_layout/seasons'
    | '/_layout/teams'
    | '/_layout/'
    | '/_layout/about/changelog'
    | '/_layout/maraton/records'
    | '/_layout/maraton/table'
    | '/_layout/search/help'
    | '/_layout/seasons/$year'
    | '/_layout/teams/$teamId'
    | '/_layout/teams/compare'
    | '/_layout/teams/list'
    | '/_layout/teams/map'
    | '/api/v1/health'
    | '/_layout/about/'
    | '/_layout/dashboard/'
    | '/_layout/login/'
    | '/_layout/logout/'
    | '/_layout/search/'
    | '/_layout/seasons/'
    | '/_layout/unauthorized/'
    | '/_layout/dashboard/games/$today'
    | '/_layout/dashboard/season/$seasonId'
    | '/_layout/dashboard/team/$teamId'
    | '/_layout/dashboard/teams/add'
    | '/_layout/maraton/records/conceded'
    | '/_layout/maraton/records/points'
    | '/_layout/maraton/records/scored'
    | '/_layout/maraton/records/stats'
    | '/_layout/maraton/records/streaks'
    | '/_layout/maraton/table/$maratonTable'
    | '/_layout/seasons/$year/$group'
    | '/_layout/seasons/$year/playoff'
    | '/_layout/teams/$teamId/$seasonId'
    | '/_layout/dashboard/$errorId/'
    | '/_layout/dashboard/newseason/'
    | '/_layout/dashboard/seasons/'
    | '/_layout/dashboard/teams/'
    | '/_layout/maraton/help/'
    | '/_layout/seasons/$year/$group/development'
    | '/_layout/seasons/$year/$group/games'
    | '/_layout/seasons/$year/$group/interval'
    | '/_layout/seasons/$year/$group/map'
    | '/_layout/seasons/$year/$group/stats'
    | '/_layout/seasons/$year/$group/tables'
    | '/_layout/seasons/$year/playoff/games'
    | '/_layout/seasons/$year/playoff/map'
    | '/_layout/seasons/$year/playoff/stats'
    | '/_layout/seasons/$year/playoff/table'
    | '/_layout/dashboard/season/$seasonId/'
    | '/_layout/seasons/$year/$group/'
    | '/_layout/teams/$teamId/latest/'
    | '/_layout/teams/$teamId/seasons/'
    | '/_layout/teams/$teamId/stats/'
    | '/_layout/teams/$teamId/tables/'
    | '/_layout/seasons/$year/$group/tables/$table'
    | '/_layout/dashboard/season/$seasonId/metadata/'
    | '/_layout/dashboard/season/$seasonId/playoffseason/'
    | '/_layout/dashboard/season/$seasonId/teamseason_/'
    | '/_layout/teams/$teamId/seasons/$seasonId/'
    | '/_layout/dashboard/season/$seasonId/games/$serieId/$serieId'
    | '/_layout/dashboard/season/$seasonId/info_/competition/$competitionId'
    | '/_layout/dashboard/season/$seasonId/info_/competition/newCompetition'
    | '/_layout/dashboard/season/$seasonId/info_/serie/$serieId'
    | '/_layout/dashboard/season/$seasonId/info_/competition/$competitionId/edit'
    | '/_layout/dashboard/season/$seasonId/info_/competition/$competitionId/newSerie'
    | '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit'
    | '/_layout/dashboard/season/$seasonId/games_/$serieId/edit/'
    | '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/$gameId'
    | '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/addGames'
    | '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/addTable'
    | '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/editParentId'
    | '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/editTable'
    | '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/games'
    | '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/generateschedule'
    | '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/newParentId'
    | '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/singlegame'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ApiV1HealthRoute: typeof ApiV1HealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/teams': {
      id: '/_layout/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof LayoutTeamsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/seasons': {
      id: '/_layout/seasons'
      path: '/seasons'
      fullPath: '/seasons'
      preLoaderRoute: typeof LayoutSeasonsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/search': {
      id: '/_layout/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutSearchRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/unauthorized/': {
      id: '/_layout/unauthorized/'
      path: '/unauthorized'
      fullPath: '/unauthorized/'
      preLoaderRoute: typeof LayoutUnauthorizedIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/seasons/': {
      id: '/_layout/seasons/'
      path: '/'
      fullPath: '/seasons/'
      preLoaderRoute: typeof LayoutSeasonsIndexRouteImport
      parentRoute: typeof LayoutSeasonsRoute
    }
    '/_layout/search/': {
      id: '/_layout/search/'
      path: '/'
      fullPath: '/search/'
      preLoaderRoute: typeof LayoutSearchIndexRouteImport
      parentRoute: typeof LayoutSearchRoute
    }
    '/_layout/logout/': {
      id: '/_layout/logout/'
      path: '/logout'
      fullPath: '/logout/'
      preLoaderRoute: typeof LayoutLogoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/login/': {
      id: '/_layout/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LayoutLoginIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard/': {
      id: '/_layout/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof LayoutDashboardIndexRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout/about/': {
      id: '/_layout/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof LayoutAboutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/teams/map': {
      id: '/_layout/teams/map'
      path: '/map'
      fullPath: '/teams/map'
      preLoaderRoute: typeof LayoutTeamsMapRouteImport
      parentRoute: typeof LayoutTeamsRoute
    }
    '/_layout/teams/list': {
      id: '/_layout/teams/list'
      path: '/list'
      fullPath: '/teams/list'
      preLoaderRoute: typeof LayoutTeamsListRouteImport
      parentRoute: typeof LayoutTeamsRoute
    }
    '/_layout/teams/compare': {
      id: '/_layout/teams/compare'
      path: '/compare'
      fullPath: '/teams/compare'
      preLoaderRoute: typeof LayoutTeamsCompareRouteImport
      parentRoute: typeof LayoutTeamsRoute
    }
    '/_layout/teams/$teamId': {
      id: '/_layout/teams/$teamId'
      path: '/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof LayoutTeamsTeamIdRouteImport
      parentRoute: typeof LayoutTeamsRoute
    }
    '/_layout/seasons/$year': {
      id: '/_layout/seasons/$year'
      path: '/$year'
      fullPath: '/seasons/$year'
      preLoaderRoute: typeof LayoutSeasonsYearRouteImport
      parentRoute: typeof LayoutSeasonsRoute
    }
    '/_layout/search/help': {
      id: '/_layout/search/help'
      path: '/help'
      fullPath: '/search/help'
      preLoaderRoute: typeof LayoutSearchHelpRouteImport
      parentRoute: typeof LayoutSearchRoute
    }
    '/_layout/maraton/table': {
      id: '/_layout/maraton/table'
      path: '/maraton/table'
      fullPath: '/maraton/table'
      preLoaderRoute: typeof LayoutMaratonTableRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/maraton/records': {
      id: '/_layout/maraton/records'
      path: '/maraton/records'
      fullPath: '/maraton/records'
      preLoaderRoute: typeof LayoutMaratonRecordsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/about/changelog': {
      id: '/_layout/about/changelog'
      path: '/about/changelog'
      fullPath: '/about/changelog'
      preLoaderRoute: typeof LayoutAboutChangelogRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/maraton/help/': {
      id: '/_layout/maraton/help/'
      path: '/maraton/help'
      fullPath: '/maraton/help/'
      preLoaderRoute: typeof LayoutMaratonHelpIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard/teams/': {
      id: '/_layout/dashboard/teams/'
      path: '/teams'
      fullPath: '/dashboard/teams/'
      preLoaderRoute: typeof LayoutDashboardTeamsIndexRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout/dashboard/seasons/': {
      id: '/_layout/dashboard/seasons/'
      path: '/seasons'
      fullPath: '/dashboard/seasons/'
      preLoaderRoute: typeof LayoutDashboardSeasonsIndexRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout/dashboard/newseason/': {
      id: '/_layout/dashboard/newseason/'
      path: '/newseason'
      fullPath: '/dashboard/newseason/'
      preLoaderRoute: typeof LayoutDashboardNewseasonIndexRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout/dashboard/$errorId/': {
      id: '/_layout/dashboard/$errorId/'
      path: '/$errorId'
      fullPath: '/dashboard/$errorId/'
      preLoaderRoute: typeof LayoutDashboardErrorIdIndexRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout/teams/$teamId/$seasonId': {
      id: '/_layout/teams/$teamId/$seasonId'
      path: '/$seasonId'
      fullPath: '/teams/$teamId/$seasonId'
      preLoaderRoute: typeof LayoutTeamsTeamIdSeasonIdRouteImport
      parentRoute: typeof LayoutTeamsTeamIdRoute
    }
    '/_layout/seasons/$year/playoff': {
      id: '/_layout/seasons/$year/playoff'
      path: '/playoff'
      fullPath: '/seasons/$year/playoff'
      preLoaderRoute: typeof LayoutSeasonsYearPlayoffRouteImport
      parentRoute: typeof LayoutSeasonsYearRoute
    }
    '/_layout/seasons/$year/$group': {
      id: '/_layout/seasons/$year/$group'
      path: '/$group'
      fullPath: '/seasons/$year/$group'
      preLoaderRoute: typeof LayoutSeasonsYearGroupRouteImport
      parentRoute: typeof LayoutSeasonsYearRoute
    }
    '/_layout/maraton/table/$maratonTable': {
      id: '/_layout/maraton/table/$maratonTable'
      path: '/$maratonTable'
      fullPath: '/maraton/table/$maratonTable'
      preLoaderRoute: typeof LayoutMaratonTableMaratonTableRouteImport
      parentRoute: typeof LayoutMaratonTableRoute
    }
    '/_layout/maraton/records/streaks': {
      id: '/_layout/maraton/records/streaks'
      path: '/streaks'
      fullPath: '/maraton/records/streaks'
      preLoaderRoute: typeof LayoutMaratonRecordsStreaksRouteImport
      parentRoute: typeof LayoutMaratonRecordsRoute
    }
    '/_layout/maraton/records/stats': {
      id: '/_layout/maraton/records/stats'
      path: '/stats'
      fullPath: '/maraton/records/stats'
      preLoaderRoute: typeof LayoutMaratonRecordsStatsRouteImport
      parentRoute: typeof LayoutMaratonRecordsRoute
    }
    '/_layout/maraton/records/scored': {
      id: '/_layout/maraton/records/scored'
      path: '/scored'
      fullPath: '/maraton/records/scored'
      preLoaderRoute: typeof LayoutMaratonRecordsScoredRouteImport
      parentRoute: typeof LayoutMaratonRecordsRoute
    }
    '/_layout/maraton/records/points': {
      id: '/_layout/maraton/records/points'
      path: '/points'
      fullPath: '/maraton/records/points'
      preLoaderRoute: typeof LayoutMaratonRecordsPointsRouteImport
      parentRoute: typeof LayoutMaratonRecordsRoute
    }
    '/_layout/maraton/records/conceded': {
      id: '/_layout/maraton/records/conceded'
      path: '/conceded'
      fullPath: '/maraton/records/conceded'
      preLoaderRoute: typeof LayoutMaratonRecordsConcededRouteImport
      parentRoute: typeof LayoutMaratonRecordsRoute
    }
    '/_layout/dashboard/teams/add': {
      id: '/_layout/dashboard/teams/add'
      path: '/teams/add'
      fullPath: '/dashboard/teams/add'
      preLoaderRoute: typeof LayoutDashboardTeamsAddRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout/dashboard/team/$teamId': {
      id: '/_layout/dashboard/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/dashboard/team/$teamId'
      preLoaderRoute: typeof LayoutDashboardTeamTeamIdRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout/dashboard/season/$seasonId': {
      id: '/_layout/dashboard/season/$seasonId'
      path: '/season/$seasonId'
      fullPath: '/dashboard/season/$seasonId'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout/dashboard/games/$today': {
      id: '/_layout/dashboard/games/$today'
      path: '/games/$today'
      fullPath: '/dashboard/games/$today'
      preLoaderRoute: typeof LayoutDashboardGamesTodayRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout/teams/$teamId/tables/': {
      id: '/_layout/teams/$teamId/tables/'
      path: '/tables'
      fullPath: '/teams/$teamId/tables/'
      preLoaderRoute: typeof LayoutTeamsTeamIdTablesIndexRouteImport
      parentRoute: typeof LayoutTeamsTeamIdRoute
    }
    '/_layout/teams/$teamId/stats/': {
      id: '/_layout/teams/$teamId/stats/'
      path: '/stats'
      fullPath: '/teams/$teamId/stats/'
      preLoaderRoute: typeof LayoutTeamsTeamIdStatsIndexRouteImport
      parentRoute: typeof LayoutTeamsTeamIdRoute
    }
    '/_layout/teams/$teamId/seasons/': {
      id: '/_layout/teams/$teamId/seasons/'
      path: '/seasons'
      fullPath: '/teams/$teamId/seasons/'
      preLoaderRoute: typeof LayoutTeamsTeamIdSeasonsIndexRouteImport
      parentRoute: typeof LayoutTeamsTeamIdRoute
    }
    '/_layout/teams/$teamId/latest/': {
      id: '/_layout/teams/$teamId/latest/'
      path: '/latest'
      fullPath: '/teams/$teamId/latest/'
      preLoaderRoute: typeof LayoutTeamsTeamIdLatestIndexRouteImport
      parentRoute: typeof LayoutTeamsTeamIdRoute
    }
    '/_layout/seasons/$year/$group/': {
      id: '/_layout/seasons/$year/$group/'
      path: '/'
      fullPath: '/seasons/$year/$group/'
      preLoaderRoute: typeof LayoutSeasonsYearGroupIndexRouteImport
      parentRoute: typeof LayoutSeasonsYearGroupRoute
    }
    '/_layout/dashboard/season/$seasonId/': {
      id: '/_layout/dashboard/season/$seasonId/'
      path: '/'
      fullPath: '/dashboard/season/$seasonId/'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdIndexRouteImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdRoute
    }
    '/_layout/seasons/$year/playoff/table': {
      id: '/_layout/seasons/$year/playoff/table'
      path: '/table'
      fullPath: '/seasons/$year/playoff/table'
      preLoaderRoute: typeof LayoutSeasonsYearPlayoffTableRouteImport
      parentRoute: typeof LayoutSeasonsYearPlayoffRoute
    }
    '/_layout/seasons/$year/playoff/stats': {
      id: '/_layout/seasons/$year/playoff/stats'
      path: '/stats'
      fullPath: '/seasons/$year/playoff/stats'
      preLoaderRoute: typeof LayoutSeasonsYearPlayoffStatsRouteImport
      parentRoute: typeof LayoutSeasonsYearPlayoffRoute
    }
    '/_layout/seasons/$year/playoff/map': {
      id: '/_layout/seasons/$year/playoff/map'
      path: '/map'
      fullPath: '/seasons/$year/playoff/map'
      preLoaderRoute: typeof LayoutSeasonsYearPlayoffMapRouteImport
      parentRoute: typeof LayoutSeasonsYearPlayoffRoute
    }
    '/_layout/seasons/$year/playoff/games': {
      id: '/_layout/seasons/$year/playoff/games'
      path: '/games'
      fullPath: '/seasons/$year/playoff/games'
      preLoaderRoute: typeof LayoutSeasonsYearPlayoffGamesRouteImport
      parentRoute: typeof LayoutSeasonsYearPlayoffRoute
    }
    '/_layout/seasons/$year/$group/tables': {
      id: '/_layout/seasons/$year/$group/tables'
      path: '/tables'
      fullPath: '/seasons/$year/$group/tables'
      preLoaderRoute: typeof LayoutSeasonsYearGroupTablesRouteImport
      parentRoute: typeof LayoutSeasonsYearGroupRoute
    }
    '/_layout/seasons/$year/$group/stats': {
      id: '/_layout/seasons/$year/$group/stats'
      path: '/stats'
      fullPath: '/seasons/$year/$group/stats'
      preLoaderRoute: typeof LayoutSeasonsYearGroupStatsRouteImport
      parentRoute: typeof LayoutSeasonsYearGroupRoute
    }
    '/_layout/seasons/$year/$group/map': {
      id: '/_layout/seasons/$year/$group/map'
      path: '/map'
      fullPath: '/seasons/$year/$group/map'
      preLoaderRoute: typeof LayoutSeasonsYearGroupMapRouteImport
      parentRoute: typeof LayoutSeasonsYearGroupRoute
    }
    '/_layout/seasons/$year/$group/interval': {
      id: '/_layout/seasons/$year/$group/interval'
      path: '/interval'
      fullPath: '/seasons/$year/$group/interval'
      preLoaderRoute: typeof LayoutSeasonsYearGroupIntervalRouteImport
      parentRoute: typeof LayoutSeasonsYearGroupRoute
    }
    '/_layout/seasons/$year/$group/games': {
      id: '/_layout/seasons/$year/$group/games'
      path: '/games'
      fullPath: '/seasons/$year/$group/games'
      preLoaderRoute: typeof LayoutSeasonsYearGroupGamesRouteImport
      parentRoute: typeof LayoutSeasonsYearGroupRoute
    }
    '/_layout/seasons/$year/$group/development': {
      id: '/_layout/seasons/$year/$group/development'
      path: '/development'
      fullPath: '/seasons/$year/$group/development'
      preLoaderRoute: typeof LayoutSeasonsYearGroupDevelopmentRouteImport
      parentRoute: typeof LayoutSeasonsYearGroupRoute
    }
    '/_layout/teams/$teamId/seasons/$seasonId/': {
      id: '/_layout/teams/$teamId/seasons/$seasonId/'
      path: '/seasons/$seasonId'
      fullPath: '/teams/$teamId/seasons/$seasonId/'
      preLoaderRoute: typeof LayoutTeamsTeamIdSeasonsSeasonIdIndexRouteImport
      parentRoute: typeof LayoutTeamsTeamIdRoute
    }
    '/_layout/dashboard/season/$seasonId/teamseason_/': {
      id: '/_layout/dashboard/season/$seasonId/teamseason_/'
      path: '/teamseason'
      fullPath: '/dashboard/season/$seasonId/teamseason/'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdTeamseasonIndexRouteImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdRoute
    }
    '/_layout/dashboard/season/$seasonId/playoffseason/': {
      id: '/_layout/dashboard/season/$seasonId/playoffseason/'
      path: '/playoffseason'
      fullPath: '/dashboard/season/$seasonId/playoffseason/'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdPlayoffseasonIndexRouteImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdRoute
    }
    '/_layout/dashboard/season/$seasonId/metadata/': {
      id: '/_layout/dashboard/season/$seasonId/metadata/'
      path: '/metadata'
      fullPath: '/dashboard/season/$seasonId/metadata/'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdMetadataIndexRouteImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdRoute
    }
    '/_layout/seasons/$year/$group/tables/$table': {
      id: '/_layout/seasons/$year/$group/tables/$table'
      path: '/$table'
      fullPath: '/seasons/$year/$group/tables/$table'
      preLoaderRoute: typeof LayoutSeasonsYearGroupTablesTableRouteImport
      parentRoute: typeof LayoutSeasonsYearGroupTablesRoute
    }
    '/_layout/dashboard/season/$seasonId/info_/serie/$serieId': {
      id: '/_layout/dashboard/season/$seasonId/info_/serie/$serieId'
      path: '/info/serie/$serieId'
      fullPath: '/dashboard/season/$seasonId/info/serie/$serieId'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdRouteImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdRoute
    }
    '/_layout/dashboard/season/$seasonId/info_/competition/newCompetition': {
      id: '/_layout/dashboard/season/$seasonId/info_/competition/newCompetition'
      path: '/info/competition/newCompetition'
      fullPath: '/dashboard/season/$seasonId/info/competition/newCompetition'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdInfoCompetitionNewCompetitionRouteImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdRoute
    }
    '/_layout/dashboard/season/$seasonId/info_/competition/$competitionId': {
      id: '/_layout/dashboard/season/$seasonId/info_/competition/$competitionId'
      path: '/info/competition/$competitionId'
      fullPath: '/dashboard/season/$seasonId/info/competition/$competitionId'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdRouteImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdRoute
    }
    '/_layout/dashboard/season/$seasonId/games/$serieId/$serieId': {
      id: '/_layout/dashboard/season/$seasonId/games/$serieId/$serieId'
      path: '/games/$serieId/$serieId'
      fullPath: '/dashboard/season/$seasonId/games/$serieId/$serieId'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdGamesSerieIdSerieIdRouteImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdRoute
    }
    '/_layout/dashboard/season/$seasonId/games_/$serieId/edit/': {
      id: '/_layout/dashboard/season/$seasonId/games_/$serieId/edit/'
      path: '/games/$serieId/edit'
      fullPath: '/dashboard/season/$seasonId/games/$serieId/edit/'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdGamesSerieIdEditIndexRouteImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdRoute
    }
    '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit': {
      id: '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit'
      path: '/edit'
      fullPath: '/dashboard/season/$seasonId/info/serie/$serieId/edit'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRouteImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdRoute
    }
    '/_layout/dashboard/season/$seasonId/info_/competition/$competitionId/newSerie': {
      id: '/_layout/dashboard/season/$seasonId/info_/competition/$competitionId/newSerie'
      path: '/newSerie'
      fullPath: '/dashboard/season/$seasonId/info/competition/$competitionId/newSerie'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdNewSerieRouteImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdRoute
    }
    '/_layout/dashboard/season/$seasonId/info_/competition/$competitionId/edit': {
      id: '/_layout/dashboard/season/$seasonId/info_/competition/$competitionId/edit'
      path: '/edit'
      fullPath: '/dashboard/season/$seasonId/info/competition/$competitionId/edit'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdEditRouteImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdRoute
    }
    '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/singlegame': {
      id: '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/singlegame'
      path: '/singlegame'
      fullPath: '/dashboard/season/$seasonId/info/serie/$serieId/edit/singlegame'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditSinglegameRouteImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRoute
    }
    '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/newParentId': {
      id: '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/newParentId'
      path: '/newParentId'
      fullPath: '/dashboard/season/$seasonId/info/serie/$serieId/edit/newParentId'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditNewParentIdRouteImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRoute
    }
    '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/generateschedule': {
      id: '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/generateschedule'
      path: '/generateschedule'
      fullPath: '/dashboard/season/$seasonId/info/serie/$serieId/edit/generateschedule'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGeneratescheduleRouteImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRoute
    }
    '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/games': {
      id: '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/games'
      path: '/games'
      fullPath: '/dashboard/season/$seasonId/info/serie/$serieId/edit/games'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGamesRouteImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRoute
    }
    '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/editTable': {
      id: '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/editTable'
      path: '/editTable'
      fullPath: '/dashboard/season/$seasonId/info/serie/$serieId/edit/editTable'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditEditTableRouteImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRoute
    }
    '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/editParentId': {
      id: '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/editParentId'
      path: '/editParentId'
      fullPath: '/dashboard/season/$seasonId/info/serie/$serieId/edit/editParentId'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditEditParentIdRouteImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRoute
    }
    '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/addTable': {
      id: '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/addTable'
      path: '/addTable'
      fullPath: '/dashboard/season/$seasonId/info/serie/$serieId/edit/addTable'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditAddTableRouteImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRoute
    }
    '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/addGames': {
      id: '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/addGames'
      path: '/addGames'
      fullPath: '/dashboard/season/$seasonId/info/serie/$serieId/edit/addGames'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditAddGamesRouteImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRoute
    }
    '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/$gameId': {
      id: '/_layout/dashboard/season/$seasonId/info_/serie/$serieId/edit/$gameId'
      path: '/$gameId'
      fullPath: '/dashboard/season/$seasonId/info/serie/$serieId/edit/$gameId'
      preLoaderRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGameIdRouteImport
      parentRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRoute
    }
  }
}

interface LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdRouteChildren {
  LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdEditRoute: typeof LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdEditRoute
  LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdNewSerieRoute: typeof LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdNewSerieRoute
}

const LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdRouteChildren: LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdRouteChildren =
  {
    LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdEditRoute:
      LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdEditRoute,
    LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdNewSerieRoute:
      LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdNewSerieRoute,
  }

const LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdRouteWithChildren =
  LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdRoute._addFileChildren(
    LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdRouteChildren,
  )

interface LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRouteChildren {
  LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGameIdRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGameIdRoute
  LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditAddGamesRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditAddGamesRoute
  LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditAddTableRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditAddTableRoute
  LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditEditParentIdRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditEditParentIdRoute
  LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditEditTableRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditEditTableRoute
  LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGamesRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGamesRoute
  LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGeneratescheduleRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGeneratescheduleRoute
  LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditNewParentIdRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditNewParentIdRoute
  LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditSinglegameRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditSinglegameRoute
}

const LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRouteChildren: LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRouteChildren =
  {
    LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGameIdRoute:
      LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGameIdRoute,
    LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditAddGamesRoute:
      LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditAddGamesRoute,
    LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditAddTableRoute:
      LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditAddTableRoute,
    LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditEditParentIdRoute:
      LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditEditParentIdRoute,
    LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditEditTableRoute:
      LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditEditTableRoute,
    LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGamesRoute:
      LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGamesRoute,
    LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGeneratescheduleRoute:
      LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditGeneratescheduleRoute,
    LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditNewParentIdRoute:
      LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditNewParentIdRoute,
    LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditSinglegameRoute:
      LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditSinglegameRoute,
  }

const LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRouteWithChildren =
  LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRoute._addFileChildren(
    LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRouteChildren,
  )

interface LayoutDashboardSeasonSeasonIdInfoSerieSerieIdRouteChildren {
  LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRouteWithChildren
}

const LayoutDashboardSeasonSeasonIdInfoSerieSerieIdRouteChildren: LayoutDashboardSeasonSeasonIdInfoSerieSerieIdRouteChildren =
  {
    LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRoute:
      LayoutDashboardSeasonSeasonIdInfoSerieSerieIdEditRouteWithChildren,
  }

const LayoutDashboardSeasonSeasonIdInfoSerieSerieIdRouteWithChildren =
  LayoutDashboardSeasonSeasonIdInfoSerieSerieIdRoute._addFileChildren(
    LayoutDashboardSeasonSeasonIdInfoSerieSerieIdRouteChildren,
  )

interface LayoutDashboardSeasonSeasonIdRouteChildren {
  LayoutDashboardSeasonSeasonIdIndexRoute: typeof LayoutDashboardSeasonSeasonIdIndexRoute
  LayoutDashboardSeasonSeasonIdMetadataIndexRoute: typeof LayoutDashboardSeasonSeasonIdMetadataIndexRoute
  LayoutDashboardSeasonSeasonIdPlayoffseasonIndexRoute: typeof LayoutDashboardSeasonSeasonIdPlayoffseasonIndexRoute
  LayoutDashboardSeasonSeasonIdTeamseasonIndexRoute: typeof LayoutDashboardSeasonSeasonIdTeamseasonIndexRoute
  LayoutDashboardSeasonSeasonIdGamesSerieIdSerieIdRoute: typeof LayoutDashboardSeasonSeasonIdGamesSerieIdSerieIdRoute
  LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdRoute: typeof LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdRouteWithChildren
  LayoutDashboardSeasonSeasonIdInfoCompetitionNewCompetitionRoute: typeof LayoutDashboardSeasonSeasonIdInfoCompetitionNewCompetitionRoute
  LayoutDashboardSeasonSeasonIdInfoSerieSerieIdRoute: typeof LayoutDashboardSeasonSeasonIdInfoSerieSerieIdRouteWithChildren
  LayoutDashboardSeasonSeasonIdGamesSerieIdEditIndexRoute: typeof LayoutDashboardSeasonSeasonIdGamesSerieIdEditIndexRoute
}

const LayoutDashboardSeasonSeasonIdRouteChildren: LayoutDashboardSeasonSeasonIdRouteChildren =
  {
    LayoutDashboardSeasonSeasonIdIndexRoute:
      LayoutDashboardSeasonSeasonIdIndexRoute,
    LayoutDashboardSeasonSeasonIdMetadataIndexRoute:
      LayoutDashboardSeasonSeasonIdMetadataIndexRoute,
    LayoutDashboardSeasonSeasonIdPlayoffseasonIndexRoute:
      LayoutDashboardSeasonSeasonIdPlayoffseasonIndexRoute,
    LayoutDashboardSeasonSeasonIdTeamseasonIndexRoute:
      LayoutDashboardSeasonSeasonIdTeamseasonIndexRoute,
    LayoutDashboardSeasonSeasonIdGamesSerieIdSerieIdRoute:
      LayoutDashboardSeasonSeasonIdGamesSerieIdSerieIdRoute,
    LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdRoute:
      LayoutDashboardSeasonSeasonIdInfoCompetitionCompetitionIdRouteWithChildren,
    LayoutDashboardSeasonSeasonIdInfoCompetitionNewCompetitionRoute:
      LayoutDashboardSeasonSeasonIdInfoCompetitionNewCompetitionRoute,
    LayoutDashboardSeasonSeasonIdInfoSerieSerieIdRoute:
      LayoutDashboardSeasonSeasonIdInfoSerieSerieIdRouteWithChildren,
    LayoutDashboardSeasonSeasonIdGamesSerieIdEditIndexRoute:
      LayoutDashboardSeasonSeasonIdGamesSerieIdEditIndexRoute,
  }

const LayoutDashboardSeasonSeasonIdRouteWithChildren =
  LayoutDashboardSeasonSeasonIdRoute._addFileChildren(
    LayoutDashboardSeasonSeasonIdRouteChildren,
  )

interface LayoutDashboardRouteChildren {
  LayoutDashboardIndexRoute: typeof LayoutDashboardIndexRoute
  LayoutDashboardGamesTodayRoute: typeof LayoutDashboardGamesTodayRoute
  LayoutDashboardSeasonSeasonIdRoute: typeof LayoutDashboardSeasonSeasonIdRouteWithChildren
  LayoutDashboardTeamTeamIdRoute: typeof LayoutDashboardTeamTeamIdRoute
  LayoutDashboardTeamsAddRoute: typeof LayoutDashboardTeamsAddRoute
  LayoutDashboardErrorIdIndexRoute: typeof LayoutDashboardErrorIdIndexRoute
  LayoutDashboardNewseasonIndexRoute: typeof LayoutDashboardNewseasonIndexRoute
  LayoutDashboardSeasonsIndexRoute: typeof LayoutDashboardSeasonsIndexRoute
  LayoutDashboardTeamsIndexRoute: typeof LayoutDashboardTeamsIndexRoute
}

const LayoutDashboardRouteChildren: LayoutDashboardRouteChildren = {
  LayoutDashboardIndexRoute: LayoutDashboardIndexRoute,
  LayoutDashboardGamesTodayRoute: LayoutDashboardGamesTodayRoute,
  LayoutDashboardSeasonSeasonIdRoute:
    LayoutDashboardSeasonSeasonIdRouteWithChildren,
  LayoutDashboardTeamTeamIdRoute: LayoutDashboardTeamTeamIdRoute,
  LayoutDashboardTeamsAddRoute: LayoutDashboardTeamsAddRoute,
  LayoutDashboardErrorIdIndexRoute: LayoutDashboardErrorIdIndexRoute,
  LayoutDashboardNewseasonIndexRoute: LayoutDashboardNewseasonIndexRoute,
  LayoutDashboardSeasonsIndexRoute: LayoutDashboardSeasonsIndexRoute,
  LayoutDashboardTeamsIndexRoute: LayoutDashboardTeamsIndexRoute,
}

const LayoutDashboardRouteWithChildren = LayoutDashboardRoute._addFileChildren(
  LayoutDashboardRouteChildren,
)

interface LayoutSearchRouteChildren {
  LayoutSearchHelpRoute: typeof LayoutSearchHelpRoute
  LayoutSearchIndexRoute: typeof LayoutSearchIndexRoute
}

const LayoutSearchRouteChildren: LayoutSearchRouteChildren = {
  LayoutSearchHelpRoute: LayoutSearchHelpRoute,
  LayoutSearchIndexRoute: LayoutSearchIndexRoute,
}

const LayoutSearchRouteWithChildren = LayoutSearchRoute._addFileChildren(
  LayoutSearchRouteChildren,
)

interface LayoutSeasonsYearGroupTablesRouteChildren {
  LayoutSeasonsYearGroupTablesTableRoute: typeof LayoutSeasonsYearGroupTablesTableRoute
}

const LayoutSeasonsYearGroupTablesRouteChildren: LayoutSeasonsYearGroupTablesRouteChildren =
  {
    LayoutSeasonsYearGroupTablesTableRoute:
      LayoutSeasonsYearGroupTablesTableRoute,
  }

const LayoutSeasonsYearGroupTablesRouteWithChildren =
  LayoutSeasonsYearGroupTablesRoute._addFileChildren(
    LayoutSeasonsYearGroupTablesRouteChildren,
  )

interface LayoutSeasonsYearGroupRouteChildren {
  LayoutSeasonsYearGroupDevelopmentRoute: typeof LayoutSeasonsYearGroupDevelopmentRoute
  LayoutSeasonsYearGroupGamesRoute: typeof LayoutSeasonsYearGroupGamesRoute
  LayoutSeasonsYearGroupIntervalRoute: typeof LayoutSeasonsYearGroupIntervalRoute
  LayoutSeasonsYearGroupMapRoute: typeof LayoutSeasonsYearGroupMapRoute
  LayoutSeasonsYearGroupStatsRoute: typeof LayoutSeasonsYearGroupStatsRoute
  LayoutSeasonsYearGroupTablesRoute: typeof LayoutSeasonsYearGroupTablesRouteWithChildren
  LayoutSeasonsYearGroupIndexRoute: typeof LayoutSeasonsYearGroupIndexRoute
}

const LayoutSeasonsYearGroupRouteChildren: LayoutSeasonsYearGroupRouteChildren =
  {
    LayoutSeasonsYearGroupDevelopmentRoute:
      LayoutSeasonsYearGroupDevelopmentRoute,
    LayoutSeasonsYearGroupGamesRoute: LayoutSeasonsYearGroupGamesRoute,
    LayoutSeasonsYearGroupIntervalRoute: LayoutSeasonsYearGroupIntervalRoute,
    LayoutSeasonsYearGroupMapRoute: LayoutSeasonsYearGroupMapRoute,
    LayoutSeasonsYearGroupStatsRoute: LayoutSeasonsYearGroupStatsRoute,
    LayoutSeasonsYearGroupTablesRoute:
      LayoutSeasonsYearGroupTablesRouteWithChildren,
    LayoutSeasonsYearGroupIndexRoute: LayoutSeasonsYearGroupIndexRoute,
  }

const LayoutSeasonsYearGroupRouteWithChildren =
  LayoutSeasonsYearGroupRoute._addFileChildren(
    LayoutSeasonsYearGroupRouteChildren,
  )

interface LayoutSeasonsYearPlayoffRouteChildren {
  LayoutSeasonsYearPlayoffGamesRoute: typeof LayoutSeasonsYearPlayoffGamesRoute
  LayoutSeasonsYearPlayoffMapRoute: typeof LayoutSeasonsYearPlayoffMapRoute
  LayoutSeasonsYearPlayoffStatsRoute: typeof LayoutSeasonsYearPlayoffStatsRoute
  LayoutSeasonsYearPlayoffTableRoute: typeof LayoutSeasonsYearPlayoffTableRoute
}

const LayoutSeasonsYearPlayoffRouteChildren: LayoutSeasonsYearPlayoffRouteChildren =
  {
    LayoutSeasonsYearPlayoffGamesRoute: LayoutSeasonsYearPlayoffGamesRoute,
    LayoutSeasonsYearPlayoffMapRoute: LayoutSeasonsYearPlayoffMapRoute,
    LayoutSeasonsYearPlayoffStatsRoute: LayoutSeasonsYearPlayoffStatsRoute,
    LayoutSeasonsYearPlayoffTableRoute: LayoutSeasonsYearPlayoffTableRoute,
  }

const LayoutSeasonsYearPlayoffRouteWithChildren =
  LayoutSeasonsYearPlayoffRoute._addFileChildren(
    LayoutSeasonsYearPlayoffRouteChildren,
  )

interface LayoutSeasonsYearRouteChildren {
  LayoutSeasonsYearGroupRoute: typeof LayoutSeasonsYearGroupRouteWithChildren
  LayoutSeasonsYearPlayoffRoute: typeof LayoutSeasonsYearPlayoffRouteWithChildren
}

const LayoutSeasonsYearRouteChildren: LayoutSeasonsYearRouteChildren = {
  LayoutSeasonsYearGroupRoute: LayoutSeasonsYearGroupRouteWithChildren,
  LayoutSeasonsYearPlayoffRoute: LayoutSeasonsYearPlayoffRouteWithChildren,
}

const LayoutSeasonsYearRouteWithChildren =
  LayoutSeasonsYearRoute._addFileChildren(LayoutSeasonsYearRouteChildren)

interface LayoutSeasonsRouteChildren {
  LayoutSeasonsYearRoute: typeof LayoutSeasonsYearRouteWithChildren
  LayoutSeasonsIndexRoute: typeof LayoutSeasonsIndexRoute
}

const LayoutSeasonsRouteChildren: LayoutSeasonsRouteChildren = {
  LayoutSeasonsYearRoute: LayoutSeasonsYearRouteWithChildren,
  LayoutSeasonsIndexRoute: LayoutSeasonsIndexRoute,
}

const LayoutSeasonsRouteWithChildren = LayoutSeasonsRoute._addFileChildren(
  LayoutSeasonsRouteChildren,
)

interface LayoutTeamsTeamIdRouteChildren {
  LayoutTeamsTeamIdSeasonIdRoute: typeof LayoutTeamsTeamIdSeasonIdRoute
  LayoutTeamsTeamIdLatestIndexRoute: typeof LayoutTeamsTeamIdLatestIndexRoute
  LayoutTeamsTeamIdSeasonsIndexRoute: typeof LayoutTeamsTeamIdSeasonsIndexRoute
  LayoutTeamsTeamIdStatsIndexRoute: typeof LayoutTeamsTeamIdStatsIndexRoute
  LayoutTeamsTeamIdTablesIndexRoute: typeof LayoutTeamsTeamIdTablesIndexRoute
  LayoutTeamsTeamIdSeasonsSeasonIdIndexRoute: typeof LayoutTeamsTeamIdSeasonsSeasonIdIndexRoute
}

const LayoutTeamsTeamIdRouteChildren: LayoutTeamsTeamIdRouteChildren = {
  LayoutTeamsTeamIdSeasonIdRoute: LayoutTeamsTeamIdSeasonIdRoute,
  LayoutTeamsTeamIdLatestIndexRoute: LayoutTeamsTeamIdLatestIndexRoute,
  LayoutTeamsTeamIdSeasonsIndexRoute: LayoutTeamsTeamIdSeasonsIndexRoute,
  LayoutTeamsTeamIdStatsIndexRoute: LayoutTeamsTeamIdStatsIndexRoute,
  LayoutTeamsTeamIdTablesIndexRoute: LayoutTeamsTeamIdTablesIndexRoute,
  LayoutTeamsTeamIdSeasonsSeasonIdIndexRoute:
    LayoutTeamsTeamIdSeasonsSeasonIdIndexRoute,
}

const LayoutTeamsTeamIdRouteWithChildren =
  LayoutTeamsTeamIdRoute._addFileChildren(LayoutTeamsTeamIdRouteChildren)

interface LayoutTeamsRouteChildren {
  LayoutTeamsTeamIdRoute: typeof LayoutTeamsTeamIdRouteWithChildren
  LayoutTeamsCompareRoute: typeof LayoutTeamsCompareRoute
  LayoutTeamsListRoute: typeof LayoutTeamsListRoute
  LayoutTeamsMapRoute: typeof LayoutTeamsMapRoute
}

const LayoutTeamsRouteChildren: LayoutTeamsRouteChildren = {
  LayoutTeamsTeamIdRoute: LayoutTeamsTeamIdRouteWithChildren,
  LayoutTeamsCompareRoute: LayoutTeamsCompareRoute,
  LayoutTeamsListRoute: LayoutTeamsListRoute,
  LayoutTeamsMapRoute: LayoutTeamsMapRoute,
}

const LayoutTeamsRouteWithChildren = LayoutTeamsRoute._addFileChildren(
  LayoutTeamsRouteChildren,
)

interface LayoutMaratonRecordsRouteChildren {
  LayoutMaratonRecordsConcededRoute: typeof LayoutMaratonRecordsConcededRoute
  LayoutMaratonRecordsPointsRoute: typeof LayoutMaratonRecordsPointsRoute
  LayoutMaratonRecordsScoredRoute: typeof LayoutMaratonRecordsScoredRoute
  LayoutMaratonRecordsStatsRoute: typeof LayoutMaratonRecordsStatsRoute
  LayoutMaratonRecordsStreaksRoute: typeof LayoutMaratonRecordsStreaksRoute
}

const LayoutMaratonRecordsRouteChildren: LayoutMaratonRecordsRouteChildren = {
  LayoutMaratonRecordsConcededRoute: LayoutMaratonRecordsConcededRoute,
  LayoutMaratonRecordsPointsRoute: LayoutMaratonRecordsPointsRoute,
  LayoutMaratonRecordsScoredRoute: LayoutMaratonRecordsScoredRoute,
  LayoutMaratonRecordsStatsRoute: LayoutMaratonRecordsStatsRoute,
  LayoutMaratonRecordsStreaksRoute: LayoutMaratonRecordsStreaksRoute,
}

const LayoutMaratonRecordsRouteWithChildren =
  LayoutMaratonRecordsRoute._addFileChildren(LayoutMaratonRecordsRouteChildren)

interface LayoutMaratonTableRouteChildren {
  LayoutMaratonTableMaratonTableRoute: typeof LayoutMaratonTableMaratonTableRoute
}

const LayoutMaratonTableRouteChildren: LayoutMaratonTableRouteChildren = {
  LayoutMaratonTableMaratonTableRoute: LayoutMaratonTableMaratonTableRoute,
}

const LayoutMaratonTableRouteWithChildren =
  LayoutMaratonTableRoute._addFileChildren(LayoutMaratonTableRouteChildren)

interface LayoutRouteChildren {
  LayoutDashboardRoute: typeof LayoutDashboardRouteWithChildren
  LayoutSearchRoute: typeof LayoutSearchRouteWithChildren
  LayoutSeasonsRoute: typeof LayoutSeasonsRouteWithChildren
  LayoutTeamsRoute: typeof LayoutTeamsRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAboutChangelogRoute: typeof LayoutAboutChangelogRoute
  LayoutMaratonRecordsRoute: typeof LayoutMaratonRecordsRouteWithChildren
  LayoutMaratonTableRoute: typeof LayoutMaratonTableRouteWithChildren
  LayoutAboutIndexRoute: typeof LayoutAboutIndexRoute
  LayoutLoginIndexRoute: typeof LayoutLoginIndexRoute
  LayoutLogoutIndexRoute: typeof LayoutLogoutIndexRoute
  LayoutUnauthorizedIndexRoute: typeof LayoutUnauthorizedIndexRoute
  LayoutMaratonHelpIndexRoute: typeof LayoutMaratonHelpIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDashboardRoute: LayoutDashboardRouteWithChildren,
  LayoutSearchRoute: LayoutSearchRouteWithChildren,
  LayoutSeasonsRoute: LayoutSeasonsRouteWithChildren,
  LayoutTeamsRoute: LayoutTeamsRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAboutChangelogRoute: LayoutAboutChangelogRoute,
  LayoutMaratonRecordsRoute: LayoutMaratonRecordsRouteWithChildren,
  LayoutMaratonTableRoute: LayoutMaratonTableRouteWithChildren,
  LayoutAboutIndexRoute: LayoutAboutIndexRoute,
  LayoutLoginIndexRoute: LayoutLoginIndexRoute,
  LayoutLogoutIndexRoute: LayoutLogoutIndexRoute,
  LayoutUnauthorizedIndexRoute: LayoutUnauthorizedIndexRoute,
  LayoutMaratonHelpIndexRoute: LayoutMaratonHelpIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ApiV1HealthRoute: ApiV1HealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
