/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTeamsIndexRouteImport } from './routes/_layout/teams/index'
import { Route as LayoutSeasonsIndexRouteImport } from './routes/_layout/seasons/index'
import { Route as LayoutSearchIndexRouteImport } from './routes/_layout/search/index'
import { Route as LayoutMaratonIndexRouteImport } from './routes/_layout/maraton/index'
import { Route as LayoutDashboardIndexRouteImport } from './routes/_layout/dashboard/index'
import { Route as LayoutAboutIndexRouteImport } from './routes/_layout/about/index'
import { Route as ApiSeasonsPageRouteImport } from './routes/api/seasons/$page'

const LayoutUnauthorizedIndexLazyRouteImport = createFileRoute(
  '/_layout/unauthorized/',
)()

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUnauthorizedIndexLazyRoute =
  LayoutUnauthorizedIndexLazyRouteImport.update({
    id: '/unauthorized/',
    path: '/unauthorized/',
    getParentRoute: () => LayoutRoute,
  } as any).lazy(() =>
    import('./routes/_layout/unauthorized/index.lazy').then((d) => d.Route),
  )
const LayoutTeamsIndexRoute = LayoutTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSeasonsIndexRoute = LayoutSeasonsIndexRouteImport.update({
  id: '/seasons/',
  path: '/seasons/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSearchIndexRoute = LayoutSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMaratonIndexRoute = LayoutMaratonIndexRouteImport.update({
  id: '/maraton/',
  path: '/maraton/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardIndexRoute = LayoutDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAboutIndexRoute = LayoutAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiSeasonsPageRoute = ApiSeasonsPageRouteImport.update({
  id: '/api/seasons/$page',
  path: '/api/seasons/$page',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/api/seasons/$page': typeof ApiSeasonsPageRoute
  '/about': typeof LayoutAboutIndexRoute
  '/dashboard': typeof LayoutDashboardIndexRoute
  '/maraton': typeof LayoutMaratonIndexRoute
  '/search': typeof LayoutSearchIndexRoute
  '/seasons': typeof LayoutSeasonsIndexRoute
  '/teams': typeof LayoutTeamsIndexRoute
  '/unauthorized': typeof LayoutUnauthorizedIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/api/seasons/$page': typeof ApiSeasonsPageRoute
  '/about': typeof LayoutAboutIndexRoute
  '/dashboard': typeof LayoutDashboardIndexRoute
  '/maraton': typeof LayoutMaratonIndexRoute
  '/search': typeof LayoutSearchIndexRoute
  '/seasons': typeof LayoutSeasonsIndexRoute
  '/teams': typeof LayoutTeamsIndexRoute
  '/unauthorized': typeof LayoutUnauthorizedIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/api/seasons/$page': typeof ApiSeasonsPageRoute
  '/_layout/about/': typeof LayoutAboutIndexRoute
  '/_layout/dashboard/': typeof LayoutDashboardIndexRoute
  '/_layout/maraton/': typeof LayoutMaratonIndexRoute
  '/_layout/search/': typeof LayoutSearchIndexRoute
  '/_layout/seasons/': typeof LayoutSeasonsIndexRoute
  '/_layout/teams/': typeof LayoutTeamsIndexRoute
  '/_layout/unauthorized/': typeof LayoutUnauthorizedIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/seasons/$page'
    | '/about'
    | '/dashboard'
    | '/maraton'
    | '/search'
    | '/seasons'
    | '/teams'
    | '/unauthorized'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/seasons/$page'
    | '/about'
    | '/dashboard'
    | '/maraton'
    | '/search'
    | '/seasons'
    | '/teams'
    | '/unauthorized'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/api/seasons/$page'
    | '/_layout/about/'
    | '/_layout/dashboard/'
    | '/_layout/maraton/'
    | '/_layout/search/'
    | '/_layout/seasons/'
    | '/_layout/teams/'
    | '/_layout/unauthorized/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ApiSeasonsPageRoute: typeof ApiSeasonsPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/unauthorized/': {
      id: '/_layout/unauthorized/'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof LayoutUnauthorizedIndexLazyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/teams/': {
      id: '/_layout/teams/'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof LayoutTeamsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/seasons/': {
      id: '/_layout/seasons/'
      path: '/seasons'
      fullPath: '/seasons'
      preLoaderRoute: typeof LayoutSeasonsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/search/': {
      id: '/_layout/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutSearchIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/maraton/': {
      id: '/_layout/maraton/'
      path: '/maraton'
      fullPath: '/maraton'
      preLoaderRoute: typeof LayoutMaratonIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard/': {
      id: '/_layout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/about/': {
      id: '/_layout/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/seasons/$page': {
      id: '/api/seasons/$page'
      path: '/api/seasons/$page'
      fullPath: '/api/seasons/$page'
      preLoaderRoute: typeof ApiSeasonsPageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAboutIndexRoute: typeof LayoutAboutIndexRoute
  LayoutDashboardIndexRoute: typeof LayoutDashboardIndexRoute
  LayoutMaratonIndexRoute: typeof LayoutMaratonIndexRoute
  LayoutSearchIndexRoute: typeof LayoutSearchIndexRoute
  LayoutSeasonsIndexRoute: typeof LayoutSeasonsIndexRoute
  LayoutTeamsIndexRoute: typeof LayoutTeamsIndexRoute
  LayoutUnauthorizedIndexLazyRoute: typeof LayoutUnauthorizedIndexLazyRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAboutIndexRoute: LayoutAboutIndexRoute,
  LayoutDashboardIndexRoute: LayoutDashboardIndexRoute,
  LayoutMaratonIndexRoute: LayoutMaratonIndexRoute,
  LayoutSearchIndexRoute: LayoutSearchIndexRoute,
  LayoutSeasonsIndexRoute: LayoutSeasonsIndexRoute,
  LayoutTeamsIndexRoute: LayoutTeamsIndexRoute,
  LayoutUnauthorizedIndexLazyRoute: LayoutUnauthorizedIndexLazyRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ApiSeasonsPageRoute: ApiSeasonsPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
